"use strict";
/* =========================================================================
   GAME — estado global, loop, maquina de estados e o funil de dano.
   Nao conhece peca nenhuma: quem sabe o que a run "e" e o BuildSystem, e quem
   sabe o que uma peca faz e o registry. Aqui so mora a simulacao.
   ========================================================================= */

const STATE = {
  MENU: "menu", PLAYING: "playing", LEVELUP: "levelup",
  GAMEOVER: "gameover", PAUSED: "paused", CHEST: "chest",
  MILESTONE: "milestone",
};

const MAX_FX_DEPTH = 8;   // teto de aninhamento de efeitos (backstop anti-loop)

/* --- The zoom of the art ---------------------------------------------------
   How many world units fit in one buffer pixel. The whole world is drawn into
   a low-res canvas and only then blown up by a WHOLE number — that is what
   makes every pixel on screen the same size as every other one.

   3 is not an arbitrary pick: a ghoul has radius 13 and used to be drawn at
   `r * 2.7` over a 13-row grid, which is 11.7 buffer pixels for 13 rows of
   art. The art had already been drawn for roughly 3x without anyone having
   written that down anywhere; PIXEL_UNIT 3 is just the game starting to
   respect the scale it was made at.

   Changing this changes the zoom of everything. `BALANCE.world.tile` has to
   stay a multiple of it, or the floor slab falls off the grid. */
const PIXEL_UNIT = 3;

/* Estilhacos da morte. `BUDGET` e o teto de particulas vivas acima do qual a
   morte volta a ser o punhado de faiscas antigo: numa leva de cinquenta
   corpos no mesmo frame, estilhacar todos custaria o frame exatamente quando
   o jogo mais precisa nao engasgar. */
const SHARD_BUDGET = 420;

class Game {
  constructor() {
    this.canvas = document.getElementById("canvas");
    this.ctx = this.canvas.getContext("2d");
    // What has to be whole is not the dpr — it is how many DEVICE pixels one
    // art pixel covers (`this.cell`, set in resize). Rounding the dpr itself
    // was the wrong lever: on a scaled Retina display devicePixelRatio is 1.5
    // or 1.7, and forcing it to 1 left the browser stretching the whole canvas
    // by 1.7 WITH filtering — which blurs everything, worst of all in motion.
    this.dpr = 1;
    this.cell = PIXEL_UNIT;

    // The world is drawn here, at low resolution. The 1/PIXEL_UNIT transform
    // lets EVERY drawing call keep speaking in world units: nobody besides
    // resize/present has to know the buffer exists.
    this.world = document.createElement("canvas");
    this.wctx = this.world.getContext("2d");
    setPixelGrid(PIXEL_UNIT);

    buildSprites();
    this.input = new InputManager();
    this.camera = new Camera();
    this.scenery = new Scenery();
    this.scenery.build();
    this.player = new Player();

    this.enemies = new Pool(() => new Enemy(), (o, ...a) => o.reset(o, ...a));
    this.projectiles = new Pool(() => new Projectile(), (o, ...a) => o.reset(o, ...a));
    this.orbs = new Pool(() => new XPOrb(), (o, ...a) => o.reset(o, ...a));
    this.areas = new Pool(() => new AreaEffect(), (o, ...a) => o.reset(o, ...a));
    this.particles = new Pool(() => new Particle(), (o, ...a) => o.reset(o, ...a));
    // ligado uma vez: a morte e o evento mais frequente do jogo e nao pode
    // alocar um closure por corpo
    this._emitShard = (x, y, vx, vy, life, color, size) =>
      this.particles.spawn(x, y, vx, vy, life, color, size, PART_SHARD);
    this.pickups = new Pool(() => new Pickup(), (o, ...a) => o.reset(o, ...a));

    this.spawner = new SpawnManager();
    this.lastBossChestAt = -BALANCE.spawn.bossChestCooldown;
    this.sfx = new Sfx();
    // rain-lofi is generated by tools/make_track.py and closes on itself (32
    // exact bars, tails folded back onto the start, room layers generated
    // circularly): native loop, no crossfade — crossfading a track that already
    // wraps doubles the beat on the way round
    this.music = new Soundtrack("audio/rain-lofi.mp3");
    this.grid = new SpatialGrid(48);
    this.events = new EventBus();
    this.vfxLayer = new VfxLayer();

    this.dots = new DotSystem(this);
    this.minions = new MinionSystem(this);
    this.build = new BuildSystem(this);

    // --- buffers reaproveitados: nada disso pode alocar por frame
    this._fxStack = [];
    this._fxDepth = 0;
    this._fxTargets = [];         // um buffer de alvos por profundidade
    this._nearD = []; this._nearE = [];
    this._chain = new Set();      // keys na cadeia de dano atual (anti-recursao)
    this.apex = null;             // a onda do Apice enquanto ela varre a tela
    this._apexQueued = null;      // eixo que encheu e ainda nao virou onda
    this.timers = [];             // efeitos agendados (Eco do Vazio)
    this.damageBy = new Map();    // key -> dano acumulado (medidor)

    // multiplicadores de jogo inteiro, escritos por BuildSystem.applyGlobals
    this.dotHaste = 1; this.dotDurationMul = 1;
    this.minionDurationMul = 1; this.minionPermanent = false;
    this.shieldPerMinion = 0; this.areaLifesteal = 0;
    this.cooldownMul = 1; this.noExternalHeal = false; this.bigHitCrit = false;
    this.dynDamage = 1;
    this.lastBigHit = null;

    this.state = STATE.MENU;
    this.bossAlive = 0;        // alimenta a intensidade da trilha
    this.selectedClass = "warlock";
    this.selectedSpeed = 1;
    this.timeScale = 1;
    this._hitstop = 0;      // segundos REAIS de simulacao congelada
    this._hitstopCd = 0;
    this.elapsed = 0;
    this.clock = 0;         // relogio de simulacao: base de TODO agendamento
    this.lastTime = 0;
    this.milestoneIdx = 0;      // proximo marco de BALANCE.milestones.at
    this.pendingMilestones = 0; // etapas vencidas e ainda nao gastas

    this.ui = new UI(this);
    this._loop = this._loop.bind(this);
    addEventListener("keydown", (e) => {
      const k = e.key.toLowerCase();
      if (k === "m") {                      // M: tudo
        this.sfx.muted = !this.sfx.muted;
        this.music.setMuted(this.sfx.muted);
      }
      if (k === "n") this.music.setMuted(!this.music.isMuted);  // N: so a trilha
      if (e.key === "Escape") this.togglePause();
    });
    /* O browser so cria AudioContext depois de um gesto do usuario, entao a
       trilha do menu comeca no primeiro clique — nao na carga da pagina. */
    addEventListener("pointerdown", () => this.enableAudio(), { once: true });
    addEventListener("resize", () => this.resize());
    this.resize();
    this.ui.buildMenu();
    requestAnimationFrame(this._loop);
  }

  enableAudio() {
    this.sfx.init();
    this.music.attach(this.sfx.ctx);
    this.music.setMuted(this.sfx.muted);
    if (this.state === STATE.MENU) this.music.setState("menu");
  }

  resize() {
    const w = innerWidth, h = innerHeight;
    this.dpr = Math.min(devicePixelRatio || 1, 3);
    // The one number that must be whole: device pixels per art pixel. Whatever
    // the display scaling is, an art pixel is a square block of `cell` real
    // pixels — never 5.1 of them.
    this.cell = Math.max(1, Math.round(PIXEL_UNIT * this.dpr));

    // +2 pixels of margin: `present` slides the blit by up to one buffer pixel
    // to scroll smoothly, and the margin is what it slides into.
    const bw = Math.ceil((w * this.dpr) / this.cell) + 2;
    const bh = Math.ceil((h * this.dpr) / this.cell) + 2;
    this.world.width = bw; this.world.height = bh;
    this.wctx.setTransform(1 / PIXEL_UNIT, 0, 0, 1 / PIXEL_UNIT, 0, 0);
    this.wctx.imageSmoothingEnabled = false;

    // Backing store in device pixels, and a CSS size that maps it 1:1 onto
    // them. Leaving the canvas at `width: 100%` would let the browser resample
    // the finished frame by whatever ratio was left over, which is filtering
    // applied on top of pixel art — the blur. The few pixels of overflow are
    // clipped by `#game`.
    this.canvas.width = bw * this.cell;
    this.canvas.height = bh * this.cell;
    this.canvas.style.width = (this.canvas.width / this.dpr) + "px";
    this.canvas.style.height = (this.canvas.height / this.dpr) + "px";
    this.ctx.setTransform(1, 0, 0, 1, 0, 0);   // setting width resets the state
    this.ctx.imageSmoothingEnabled = false;

    // The camera sees the whole buffer, margin included: otherwise the scenery
    // stops drawing exactly on the strip the blit slides into.
    this.camera.resize(bw * PIXEL_UNIT, bh * PIXEL_UNIT);
  }

  /* The only place that scales up: one copy of the buffer to the screen, every
     art pixel a square block of `cell` device pixels, no filtering.

     The blit is offset by whatever the camera had left over after snapping to
     the grid, converted to device pixels. That is what makes the world scroll
     smoothly: without it the whole screen jumps a full art pixel at a time,
     and a lerped camera makes those jumps irregular — walking looked like it
     stuttered. With it the motion has the granularity of the display while the
     art keeps the granularity of the grid. */
  present() {
    const ctx = this.ctx, cam = this.camera, C = this.cell;
    const dx = Math.round(((cam.left - cam.rawLeft) / PIXEL_UNIT) * C);
    const dy = Math.round(((cam.top - cam.rawTop) / PIXEL_UNIT) * C);
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(this.world, 0, 0, this.world.width, this.world.height,
                  dx, dy, this.world.width * C, this.world.height * C);
  }

  /* --- consultas espaciais ------------------------------------------------
     Todas passam pelo grid. A varredura linear que existia antes rodava por
     projetil teleguiado por frame e nao aguentaria o catalogo novo. */

  nearestEnemy(x, y, maxDist) {
    return this.grid.nearest(x, y, maxDist || 4000, null, null);
  }
  nearestEnemyExcept(x, y, maxDist, exclude) {
    return this.grid.nearest(x, y, maxDist || 4000, exclude, null);
  }
  nearestRangedEnemy(x, y, maxDist) {
    return this.grid.nearest(x, y, maxDist || 4000, null, (e) => !!e.type.ranged);
  }
  /* Ate `count` inimigos mais proximos. Insercao ordenada num par de buffers
     reaproveitados: nunca ordena a horda inteira e nunca aloca. */
  nearestEnemies(x, y, maxDist, count) {
    const ds = this._nearD, es = this._nearE;
    ds.length = 0; es.length = 0;
    const md2 = maxDist * maxDist;
    this.grid.forRadius(x, y, maxDist, (e) => {
      if (e.hp <= 0 || e.charmed) return;
      const dx = e.x - x, dy = e.y - y, d2 = dx * dx + dy * dy;
      if (d2 > md2) return;
      if (ds.length >= count && d2 >= ds[ds.length - 1]) return;
      let i = Math.min(ds.length, count - 1);
      while (i > 0 && ds[i - 1] > d2) { ds[i] = ds[i - 1]; es[i] = es[i - 1]; i--; }
      ds[i] = d2; es[i] = e;
      if (ds.length > count) { ds.length = count; es.length = count; }
    });
    return es;
  }

  /* --- servicos usados pelos efeitos -------------------------------------- */

  /* Um fato visual, duas consumidoras: a camada que desenha e a que toca. Nao
     existe um registry de som por peca — seriam duas listas para divergir, e a
     que envelhecesse deixaria uma peca muda em silencio. Evento novo em tela
     exige voz nova, e `driver_vfx` reprova evento sem ela. */
  emitVfx(kind, x, y, r, color, x2, y2) {
    this.vfxLayer.emit(kind, x, y, r, color, x2, y2);
    this.emitSfx(kind, x, y, r / 220);
  }

  /* A distancia so e calculada depois que a voz passou pelo gap: `say` recusa
     a maioria das chamadas numa build madura, e a raiz quadrada nao pode ser
     paga por chamada recusada. */
  emitSfx(name, x, y, size) {
    if (!this.sfx.can(name)) return;
    const p = this.player, dx = x - p.x, dy = y - p.y;
    this.sfx.say(name, { dist: Math.sqrt(dx * dx + dy * dy), size: size });
  }

  queueApex(axisId) { this._apexQueued = axisId; }

  schedule(delay, fn) { this.timers.push({ at: this.clock + delay, fn }); }

  healPlayer(amount, force) {
    if (amount <= 0) return;
    if (this.noExternalHeal && !force) return;   // custo do capstone Tirania
    const p = this.player;
    p.hp = Math.min(p.maxHp, p.hp + amount);
  }

  // Desmancha projeteis hostis num raio (Nether Ward).
  reflectProjectiles(x, y, radius, damage, blastRadius, c) {
    const list = this.projectiles.active;
    const r2 = radius * radius;
    let hit = 0;
    for (let i = 0; i < list.length; i++) {
      const p = list[i];
      if (!p.hostile || p.dead) continue;
      const dx = p.x - x, dy = p.y - y;
      if (dx * dx + dy * dy > r2) continue;
      p.dead = true;
      hit++;
      if (damage > 0) {
        const n = pushCtx(this);
        n.key = c.key; n.color = c.color; n.now = c.now;
        n.x = p.x; n.y = p.y; n.target = null;
        EFFECTS.damage_instant(this, { amount: damage, radius: blastRadius || 60 }, n);
        popCtx(this);
      }
    }
    if (hit) this.emitVfx("shock", x, y, radius, c.color);
  }

  /* Converte um inimigo em aliado: ele sai do pool de inimigos e volta como
     demonio. Mais simples e mais barato que ensinar o Enemy a lutar contra os
     proprios — e o resultado em tela e o mesmo. */
  convertEnemy(e, duration, c) {
    if (!e || e.hp <= 0 || e.type.boss) return;
    e.charmed = true;
    e.hp = 0;                                  // sera colhido por killDeadEnemies
    e.noReward = true;
    const kind = e.radius > 20 ? "felguard" : e.radius > 13 ? "dreadstalker" : "imp";
    const n = pushCtx(this);
    n.key = c.key; n.color = c.color; n.now = c.now;
    n.x = e.x; n.y = e.y; n.target = null;
    EFFECTS.summon(this, {
      kind, ai: "chase", count: 1, cap: 24, duration,
      damage: Math.max(12, e.touchDps * 2.5), attackInterval: 0.8, range: 400,
      big: e.radius > 20,
    }, n);
    popCtx(this);
    this.emitVfx("summon", e.x, e.y, 40, c.color);
    /* A coleira. Escravizar devolvia exatamente o que invocar devolvia — o
       mesmo anel fechando e o mesmo demonio nascendo —, e as duas coisas nao
       sao a mesma: uma conjura do nada e a outra TOMA um corpo que ja estava
       ali. O filamento saindo do warlock e o que diz de quem aquilo passou a
       ser. */
    this.emitVfx("link", this.player.x, this.player.y, 0, c.color, e.x, e.y);
  }

  /* --- o funil de dano ----------------------------------------------------
     TODO dano em inimigo passa por aqui. `key` e a identidade estavel da peca:
     chave do medidor, guarda anti-recursao e origem dos eventos.

     A guarda: enquanto os eventos de um acerto estao sendo despachados, a key
     fica em `_chain`, e um trigger reativo daquela mesma key nao dispara. E a
     generalizacao do antigo `source !== "corruption"` — sem ela, um DoT que
     aplica DoT trava o browser. */
  damageEnemy(e, amount, key, big, dotKey) {
    if (!e || e.hp <= 0 || amount <= 0) return 0;

    let amt = amount * this.dynDamage;
    if (e.marked && this.clock < e.markedUntil) amt *= 1 + e.marked;
    if (big && this.bigHitCrit) amt *= 2;      // capstone Nihilam

    e.hp -= amt;
    e.hitFlash = 0.1;
    if (key) this.damageBy.set(key, (this.damageBy.get(key) || 0) + amt);

    if (this.areaLifesteal > 0 && !dotKey) this.healPlayer(amt * this.areaLifesteal);

    const reenter = key && this._chain.has(key);
    if (!reenter && key) this._chain.add(key);

    if (big) {
      this.lastBigHit = { amount: amt, key };
      // o golpe viajou do jogador para o alvo: a camera vai junto, e assim o
      // soco diz ONDE bateu, e nao apenas que bateu
      this.addShake(9, e.x - this.player.x, e.y - this.player.y);
      this.addHitstop(BALANCE.camera.hitstop.big);
      this.emitSfx("crit", e.x, e.y, 0.5);
      this.events.emit(EVENTS.BIG_HIT, { enemy: e, amount: amt, key });
    }
    this.events.emit(EVENTS.ENEMY_HIT, { enemy: e, amount: amt, key });
    if (e.hp > 0 && e.hp / e.maxHp <= 0.2) {
      this.events.emit(EVENTS.ENEMY_LOW, { enemy: e, pct: e.hp / e.maxHp });
    }

    if (!reenter && key) this._chain.delete(key);
    return amt;
  }

  damagePlayer(amount, source) {
    const p = this.player;
    const dealt = p.takeDamage(amount);
    if (dealt > 0) this.events.emit(EVENTS.PLAYER_DAMAGED, { amount: dealt, source });
    return dealt;
  }

  /* --- ciclo de vida ------------------------------------------------------ */

  start() {
    const cls = CLASSES[this.selectedClass];
    this.player.reset(cls);
    this.enemies.clear(); this.projectiles.clear(); this.orbs.clear();
    this.areas.clear(); this.particles.clear(); this.pickups.clear();
    this.dots.reset(); this.minions.reset(); this.vfxLayer.reset();
    this.scenery.reset();
    this.events.clear();
    this.spawner.reset();
    this.timers.length = 0;
    this.damageBy.clear();
    this._chain.clear();
    this._fxDepth = 0;
    this._hitstop = 0;
    this._hitstopCd = 0;
    this.reapHeat = 0;
    this.reapTier = 0;
    this.apex = null;
    this._apexQueued = null;
    this.comboCount = 0;
    this.comboUntil = 0;
    this.comboBest = 0;
    this.comboPulseAt = -99;
    this.camera.resetShake();
    this.lastBigHit = null;
    this.build.reset();
    this.elapsed = 0;
    this.clock = 0;
    this.milestoneIdx = 0;
    this.pendingMilestones = 0;
    this.bossAlive = 0;
    this.lastBossChestAt = -BALANCE.spawn.bossChestCooldown;
    this.timeScale = this.selectedSpeed;
    this.camera.x = 0; this.camera.y = 0;
    this.camera.follow(this.player, 1, true);

    for (const id of cls.starting) this.build.acquirePiece(id, true);
    this.build.afterChange();

    this.enableAudio();
    this.music.restart();
    this.music.setState("playing");
    this.state = STATE.PLAYING;
    this.ui.onStart();
  }

  gameOver() {
    // Soulstone: uma carga levanta o player em vez de encerrar a run.
    if (this.player.reviveCharges > 0) {
      this.player.reviveCharges--;
      this.player.hp = this.player.maxHp * 0.55;
      this.player.addShield(80);
      this.addShake(20);
      this.emitVfx("heal", this.player.x, this.player.y, 90, PIECES.soulstone.color);
      this.sfx.levelUp();
      this.ui.toast({ head: "Soulstone", axis: PIECES.soulstone.axis,
        name: "Uma alma guardada pagou o preço no seu lugar." });
      return;
    }
    this.state = STATE.GAMEOVER;
    this.music.setState("gameover");
    this.sfx.gameOver();
    this.ui.onGameOver();
  }

  togglePause() {
    if (this.state === STATE.PLAYING) {
      this.state = STATE.PAUSED;
      this.music.setState("paused");
      this.ui.onPause();
    } else if (this.state === STATE.PAUSED) this.resume();
  }
  resume() { this.ui.hidePause(); this.music.setState("playing"); this.state = STATE.PLAYING; }
  quitToMenu() { this.ui.toMenu(); this.music.setState("menu"); this.state = STATE.MENU; }

  /* `dx,dy` apontam para ONDE o golpe foi: a camera e empurrada no mesmo
     sentido em que ele viajou. Quem nao tem posicao (subir de nivel, virada de
     fase) omite os dois e recebe so a cauda de tremor. */
  addShake(mag, dx, dy) { this.camera.addTrauma(mag, dx, dy); }

  /* Congela a simulacao por alguns milissegundos REAIS. E a coisa mais barata
     que existe num jogo de acao para fazer um golpe ATERRISSAR em vez de
     apenas acontecer: o frame em que ele conecta fica no ar tempo suficiente
     para ser visto.

     Segundos reais, nunca `clock`: o relogio e escalado, entao um stop de 50ms
     duraria 150ms no timeScale 3. E limitado por cadencia, porque este jogo
     poe dezenas de acertos grandes em tela ao mesmo tempo e um stop por acerto
     e uma apresentacao de slides. `force` e para o que acontece uma vez por
     run e nao pode ser comido pela cadencia de outro evento. */
  addHitstop(d, force) {
    if (this._hitstopCd > 0 && !force) return;
    this._hitstop = Math.max(this._hitstop, d);
    this._hitstopCd = BALANCE.camera.hitstop.cooldown;
  }

  /* O corpo se DESFAZ, e nas cores dele. Ate aqui a morte eram seis bolinhas
     redondas em `type.color` — iguais para os dezoito inimigos, e redondas em
     cima de arte em grade inteira.

     Duas travas, e as duas sao a regra "escala com a quantidade":

     - O numero de estilhacos sai do porte do corpo, nao do gosto: um ghoul se
       desfaz em oito pedacos e um Aniquilador em vinte e quatro.
     - Existe ORCAMENTO. A morte e o evento mais frequente do jogo — numa leva
       de cinquenta corpos no mesmo frame, estilhacar todos custaria o frame
       inteiro, e justamente no momento em que o jogo precisa nao engasgar. O
       que passa do teto morre como antes: pouca coisa, mas nao nada. */
  shatterEnemy(e, heft) {
    const room = SHARD_BUDGET - this.particles.active.length;
    const n = room > 0
      ? shardBurst(e.type.id, e.x, e.y, e.radius * (e.type.art || 2.7), heft, room, this._emitShard)
      : 0;
    // sprite sem grade, ou orcamento estourado: o punhado de faiscas antigo.
    // Pouca coisa, mas nao nada — corpo que some sem nada le como bug de pool.
    if (!n) this.spawnParticles(e.x, e.y, e.type.color, room > 3 ? 4 : 1);
  }

  /* A ceifa: o jogo dizendo que ISSO acabou de acontecer. Ver BALANCE.reap. */
  tickReap(dt) {
    const R = BALANCE.reap;
    if (this.reapHeat <= 0) return;
    this.reapHeat = Math.max(0, this.reapHeat - R.cool * dt);
    // rearma quando a leva esfria: sem isso um massacre longo anuncia o mesmo
    // degrau a cada corpo que cai
    while (this.reapTier > 0 && this.reapHeat < R.tiers[this.reapTier - 1] * R.reset) {
      this.reapTier--;
    }
  }

  onReapKill() {
    const R = BALANCE.reap;
    this.reapHeat++;
    let t = 0;
    for (let i = R.tiers.length - 1; i >= 0; i--) {
      if (this.reapHeat >= R.tiers[i]) { t = i + 1; break; }
    }
    if (t <= this.reapTier) return;
    this.reapTier = t;
    const p = this.player;
    this.emitVfx("reap", p.x, p.y, R.radius[t - 1], this.buildColor());
    this.addShake(R.shake[t - 1]);
  }

  /* --- o Apice ------------------------------------------------------------
     Um eixo chegou a 15: a onda sai do corpo e varre o que esta em tela. Ver
     BALANCE.apex para o porque de cada numero. */
  startApex(axisId) {
    const p = this.player, cam = this.camera;
    /* O raio e o canto VISIVEL mais distante, medido do jogador. A camera
       persegue com lerp, entao ele quase nunca esta no centro dela: usar
       metade da diagonal deixaria viva a faixa de horda do lado para onde a
       camera ainda esta andando. */
    const rx = Math.abs(p.x - cam.x) + cam.w / 2;
    const ry = Math.abs(p.y - cam.y) + cam.h / 2;
    const r = Math.sqrt(rx * rx + ry * ry);
    // ancorado onde a onda NASCEU: ela ja saiu do corpo, entao andar durante a
    // varredura nao arrasta o alcance junto
    this.apex = { x: p.x, y: p.y, r, t: 0, front: 0, bit: new Set() };
    this.emitVfx("apex", p.x, p.y, r, AXIS_PALETTE[axisId].light);
    this.addShake(BALANCE.apex.shake);
    // `force`: acontece uma vez por run e nao pode ser comido pela cadencia de
    // um acerto qualquer que tenha caido no mesmo quarto de segundo
    this.addHitstop(BALANCE.camera.hitstop.boss, true);
  }

  tickApex(dt) {
    const A = this.apex;
    if (!A) return;
    const B = BALANCE.apex;
    A.t += dt;
    const k = Math.min(1, A.t / B.sweep);
    const front = A.r * apexFront(k);
    A.front = front;

    /* A frente e uma FRONTEIRA, e nao um anel: morre tudo o que esta dentro
       dela, nao so o que entrou nela neste tique.

       Cobrar so o anel entre a frente de antes e a de agora e a versao obvia,
       e ela esta errada porque o alvo se MEXE: a horda anda para dentro. Um
       ghoul que a onda ultrapassou enquanto ele estava a 660 unidades caminha
       para 620 no tique seguinte, cai atras da frente sem nunca ter estado no
       anel, e sobrevive ao evento que existe para limpar a tela. Medido: doze
       de doze vivos na borda.

       Para o corpo comum a repeticao nao custa nada (ele ja morreu, e
       `hp <= 0` corta na primeira linha). Quem precisa de guarda e o chefe,
       que sobrevive a mordida: sem o `Set` ele levaria `bossFrac` a cada
       sub-step, e sao varios por quadro.

       Pelo grid, nunca varrendo `enemies.active`: o raio aqui e de tela
       inteira, mas a lista chega a 4400 corpos e isto roda em todo sub-step
       da meia-segunda. */
    this.grid.forRadius(A.x, A.y, front, (e) => {
      if (e.hp <= 0 || e.charmed) return;
      const dx = e.x - A.x, dy = e.y - A.y;
      if (dx * dx + dy * dy > front * front) return;
      if (e.type.boss) {
        if (A.bit.has(e.gen)) return;
        A.bit.add(e.gen);
        this.damageEnemy(e, e.maxHp * B.bossFrac, "apex", true);
      } else {
        // pelo funil, para o abate render XP, estilhaco, ceifa e os reativos
        // de morte. `dynDamage` divide de volta o multiplicador global: o que
        // esta declarado e "morre", nao "leva tanto".
        this.damageEnemy(e, e.hp / Math.max(0.05, this.dynDamage) + 1, "apex");
      }
    });
    if (k >= 1) this.apex = null;
  }

  /* A cadeia: o mesmo fato da ceifa, dito em numero. Ver BALANCE.combo.

     Ela vive no relogio de SIMULACAO como todo o resto do agendamento: a
     janela de um segundo tem que valer um segundo de jogo, senao o modo
     rapido daria o triplo de folga para manter a conta viva. */
  onComboKill() {
    const C = BALANCE.combo;
    this.comboCount = this.clock <= this.comboUntil ? this.comboCount + 1 : 1;
    this.comboUntil = this.clock + C.window;
    if (this.comboCount > this.comboBest) this.comboBest = this.comboCount;
    // o salto so rearma depois de terminar: ver o porque em BALANCE.combo
    if (this.comboCount >= C.min && this.clock - this.comboPulseAt >= C.pulse) {
      this.comboPulseAt = this.clock;
    }
  }

  tickCombo() {
    if (this.comboCount && this.clock > this.comboUntil) this.comboCount = 0;
  }

  /* O degrau da cadeia, 0..tiers.length — quem decide o tamanho do numero e o
     tamanho do salto. */
  comboTier() {
    const t = BALANCE.combo.tiers;
    for (let i = t.length - 1; i >= 0; i--) if (this.comboCount >= t[i]) return i + 1;
    return 0;
  }

  /* 1 no quadro do abate, 0 quando o salto acabou. Nao ha estado decaindo por
     frame aqui de proposito: `pulse` e a duracao inteira dele, entao a curva
     sai de uma subtracao. */
  comboPulse() {
    const k = (this.clock - this.comboPulseAt) / BALANCE.combo.pulse;
    return k >= 1 || k < 0 ? 0 : 1 - k;
  }

  /* A cor do eixo em que a build mais investiu. A ceifa nao pertence a uma
     peca, mas tambem nao pode inventar matiz: cor continua sendo predicado de
     eixo, e o que ela diz e "a SUA build acabou de fazer isso". */
  buildColor() {
    let best = null, top = -1;
    for (const a in this.build.axis) {
      if (this.build.axis[a] > top) { top = this.build.axis[a]; best = a; }
    }
    const pal = best && AXIS_PALETTE[best];
    return pal ? pal.light : CLASSES[this.selectedClass].color;
  }

  spawnParticles(x, y, color, count) {
    for (let i = 0; i < count; i++) {
      const a = Math.random() * Math.PI * 2;
      const sp = 40 + Math.random() * 120;
      this.particles.spawn(x, y, Math.cos(a) * sp, Math.sin(a) * sp,
        0.3 + Math.random() * 0.3, color, 2 + Math.random() * 2.5);
    }
  }

  onBossSpawn(count = 1) {
    this.bossAlive += count;
    this.addShake(10 + (count - 1) * 4);
    this.sfx.boss();
    this.ui.toast({ head: "Chefe",
      name: count > 1 ? `${count} Dreadlords na Distorção` : "Dreadlord na Distorção" });
  }

  onHardPhase() {
    this.addShake(14);
    this.sfx.boss();
    this.ui.toast({ head: "A Distorção rasgou",
      name: "A horda acelera a cada 15s" });
  }

  /* --- loop ---------------------------------------------------------------
     dt real -> clamp -> timeScale -> passos de no maximo 0.025s.
     update(dt) roda VARIAS vezes por frame; por isso todo agendamento usa
     `this.clock` e nunca contagem de frames. */
  _loop(now) {
    requestAnimationFrame(this._loop);
    if (!this.lastTime) this.lastTime = now;
    let dt = (now - this.lastTime) / 1000;
    this.lastTime = now;
    if (dt > 0.1) dt = 0.1;

    /* O hitstop mora aqui e nao em `update`: ele para a SIMULACAO, e a camera
       e a apresentacao dela. Segurar as duas junto esconderia o soco de camera
       exatamente no acerto que o gerou. */
    if (this._hitstopCd > 0) this._hitstopCd -= dt;
    let scale = this.timeScale;
    if (this._hitstop > 0) { this._hitstop -= dt; scale = 0; }

    let total = dt * scale;
    while (total > 0) {
      const step = Math.min(0.025, total);
      this.update(step);
      total -= step;
    }
    this.vfxLayer.update(dt * scale);
    /* Tremor em tempo real, fora de `update`: ele nao e simulacao. Preso ao
       relogio escalado a cauda morria 3x mais rapido no timeScale 3, e preso
       ao `update` o tremor que a tela de level up pede ficava parado esperando
       a run voltar em vez de tocar na hora. */
    this.camera.updateShake(dt);
    this.music.update(dt);   // relogio do audio, nao do jogo: ignora timeScale
    this._frameDt = dt;      // brasas e vinheta vivem em tempo real
    this.render();
  }

  update(dt) {
    if (this.state !== STATE.PLAYING) return;
    this.elapsed += dt;
    this.clock += dt;

    /* O Apice nasce EM FILA e nao no `addAxis` que o descobriu: aquele ponto
       do codigo roda com a tela de etapa aberta, o canvas apagado e o mundo
       parado — a onda sairia por cima de preto chapado, matando uma horda que
       o jogador nao esta vendo. Aqui ela sai no primeiro quadro de jogo de
       volta, que e o quadro em que ela tem plateia. */
    if (this._apexQueued) {
      const a = this._apexQueued;
      this._apexQueued = null;
      this.startApex(a);
    }

    this.player.update(dt, this.input);
    this.applyPassives(dt);
    this.build.updateDynamic();

    this.updateMilestones();
    this.spawner.update(dt, this);
    this.updateEnemies(dt);          // move + preenche o grid + contato
    this.tickApex(dt);               // a onda do Apice, com o grid recem-feito
    this.minions.update(dt, this.clock);
    this.build.tick(dt, this.clock); // triggers de todas as pecas
    this.dots.update(this.clock);    // scheduler por timestamp
    this.updateProjectiles(dt);
    this.updateAreas(dt);
    this.runTimers();
    this.killDeadEnemies();
    this.updateOrbs(dt);
    this.updatePickups(dt);
    this.updateParticles(dt);
    this.tickReap(dt);
    this.tickCombo();
    // buff que DURA nao se desenha por evento: evento por pulso e a forma
    // errada para um estado. O render precisa do relogio, e o Player nao o tem.
    this.player.rushing = this.player.speedBoostUntil > this.clock;

    this.camera.follow(this.player, dt);
    // o mundo apodrece junto com a run: veios mais vivos, mais brasa no ar
    this.scenery.corruption = clamp(this.elapsed / BALANCE.spawn.hardAt, 0, 1);
    this.music.setIntensity(this.musicIntensity());
    this.ui.updateHUD();

    if (this.player.hp <= 0) { this.gameOver(); return; }

    /* Etapa antes de nivel. As duas telas param o jogo, entao a ordem so
       importa quando as duas caem no mesmo frame — e ai a etapa vai primeiro
       porque ela e a rara: um marco engolido pela fila de level ups perderia
       o palco que ele existe para ter. */
    /* A onda segura as duas telas. Ela mata centenas de corpos, entao o XP
       que ela derruba abre level up quase sempre no meio da varredura — e uma
       carta subindo por cima do evento cortaria justamente o pagamento da
       unica escolha da run que nao volta. Os niveis esperam 0,55s na fila.

       Nao e so apresentacao: a tela para `update` e nao para `VfxLayer`, entao
       a frente da simulacao congelaria enquanto o anel continuaria correndo, e
       as duas coisas que `apexFront` existe para manter iguais divergiriam. */
    if (this.apex) return;
    if (this.pendingMilestones > 0) { this.ui.openMilestone(); return; }
    if (this.player.pendingLevels > 0) this.ui.openLevelUp();
  }

  /* Marcos de tempo: a batida lenta e a unica fonte de ponto de eixo.

     Marca em FILA (`pendingMilestones++`) em vez de abrir a tela aqui: este
     ponto do update esta no meio da simulacao, e um `state` trocado aqui
     deixaria o resto do frame rodando com o jogo ja "parado". Quem abre e o
     fim do update, junto com o level up.

     A fila tambem cobre o caso raro de dois marcos no mesmo frame (timeScale 3
     com um travamento): o segundo espera sua vez em vez de sumir. */
  updateMilestones() {
    /* A condicao de parada e a POOL, nao a tabela.

       Enquanto `at` era o fim da linha, quem levava spell nas etapas terminava
       a run com ponto de eixo no bolso e sem tela nenhuma para gasta-lo:
       `pieceDiscount` atrasa o ritmo em um ponto por spell, entao sete spells
       deixavam sete pontos parados. Medido, runs acabando em 12/20 e 13/20 —
       ponto que existe, aparece no painel, e nao tem como virar nada. */
    if (this.build.axisLeft <= 0) return;
    // Teto de fila: com `tailEvery` pequeno e um travamento longo, o laco
    // poderia enfileirar dezenas de telas de uma vez.
    while (this.pendingMilestones < 3 && this.elapsed >= this.milestoneTimeAt(this.milestoneIdx)) {
      this.milestoneIdx++;
      this.pendingMilestones++;
    }
  }

  /* Quando o marco `idx` acontece. Cadencia fixa, sem tabela: quem decide
     quantos marcos a run tem e a POOL, nao uma lista de horarios.

     Uma funcao so para os dois usos (disparar e contar no HUD): duas copias
     divergiriam na primeira vez que a cadencia mudasse, e o HUD passaria a
     contar para um marco que nao e o que vai disparar. */
  milestoneTimeAt(idx) {
    const M = BALANCE.milestones;
    return M.first + idx * M.every;
  }

  /* Segundos ate o proximo marco, ou null quando nao ha mais ponto a dar. E o
     que o HUD mostra: marco que chega sem aviso nao estrutura ritmo nenhum — o
     jogador precisa poder ver a decisao se aproximando. */
  nextMilestoneIn() {
    if (this.build.axisLeft <= 0) return null;
    return Math.max(0, this.milestoneTimeAt(this.milestoneIdx) - this.elapsed);
  }

  /* A trilha acompanha a pressao real da run, nao um cronometro proprio:
     sobe devagar com o tempo, salta na fase dura e vai ao teto com chefe em
     campo. Quem le isso e Music.setIntensity, que suaviza a transicao. */
  musicIntensity() {
    if (this.bossAlive > 0) return 1;
    let k = Math.min(0.72, this.elapsed / 400);
    if (this.elapsed >= BALANCE.spawn.hardAt) k = Math.max(k, 0.62);
    return k;
  }

  runTimers() {
    const t = this.timers;
    for (let i = 0; i < t.length; i++) {
      if (this.clock < t[i].at) continue;
      const fn = t[i].fn;
      t[i] = t[t.length - 1];
      t.pop(); i--;
      fn();
    }
  }

  applyPassives(dt) {
    const p = this.player;
    let speed = p.baseSpeed;
    if (this.clock < (p.speedBoostUntil || 0)) speed *= p.speedBoost;
    p.speed = speed;
    p.basePickup = p.pickupForLevel();
    p.pickupRange = p.basePickup;

    // Vinculo de Alma: teto de escudo cresce com o exercito em campo
    if (this.shieldPerMinion > 0) {
      const cap = p.maxHp * this.shieldPerMinion * this.minions.count();
      p.maxShield = Math.max(p.maxShield, cap);
      if (cap > 0) p.shield = Math.min(Math.max(p.shield, 0) + cap * dt * 0.5, cap);
    }
  }

  updateEnemies(dt) {
    const list = this.enemies.active;
    const p = this.player;
    const now = this.clock;
    this.grid.clear();
    for (let i = 0; i < list.length; i++) {
      const e = list[i];
      e.update(dt, p, now);
      this.grid.insert(e);

      if (now < e.stunUntil) continue;

      const dx = p.x - e.x, dy = p.y - e.y;
      const rr = p.radius + e.radius;
      if (dx * dx + dy * dy < rr * rr) {
        let touch = e.touchDps;
        if (now < (e.weakUntil || 0)) touch *= e.weakFactor;
        this.damagePlayer(touch * dt, "touch");
      }

      if (e.type.ranged) {
        e.shootTimer -= dt;
        const t = e.type;
        if (e.shootTimer <= 0 && dx * dx + dy * dy < t.shootRange * t.shootRange) {
          e.shootTimer = t.shootInterval * (now < (e.weakUntil || 0) ? 1 / e.weakFactor : 1);
          const a = Math.atan2(p.y - e.y, p.x - e.x);
          this.projectiles.spawn({
            x: e.x, y: e.y,
            vx: Math.cos(a) * t.shootSpeed, vy: Math.sin(a) * t.shootSpeed,
            damage: e.shootDamage, radius: 7, color: "#ff4db8",
            source: "enemy", life: 3, pierce: 0, hostile: true,
          });
        }
      }
    }
    this.separateEnemies();
  }

  // separação leve reaproveitando o grid já populado — sem O(n²)
  separateEnemies() {
    const list = this.enemies.active;
    for (let i = 0; i < list.length; i++) {
      const e = list[i];
      this.grid.forNear(e.x, e.y, (o) => {
        if (o === e) return;
        let dx = e.x - o.x, dy = e.y - o.y;
        const minD = e.radius + o.radius;
        const d2 = dx * dx + dy * dy;
        if (d2 > 0 && d2 < minD * minD) {
          const d = Math.sqrt(d2);
          const push = (minD - d) * 0.5;
          dx /= d; dy /= d;
          e.x += dx * push; e.y += dy * push;
          o.x -= dx * push; o.y -= dy * push;
        }
      });
    }
  }

  /* Marca-e-varre, como os DoTs: o impacto de um projetil pode disparar um
     reativo que cria OUTRO projetil neste mesmo pool. `n` congela o tamanho
     para que o recem-nascido nao ande no frame em que foi criado. */
  updateProjectiles(dt) {
    const list = this.projectiles.active;
    const pl = this.player;
    const n = list.length;
    for (let i = 0; i < n; i++) {
      const p = list[i];
      if (p.dead) continue;

      if (p.homing) {
        /* The fan and the homing cancel each other out: re-aiming every frame
           closes a 0.21rad spread in two frames, so a burst of 4 reads as one
           fat projectile. `fanDelay` buys the fan the time to be seen — only
           shots born in a fan carry it, a lone bolt stays stubborn from frame
           one. It burns simulation time, so timeScale scales it like the
           rest. */
        if (p.fanDelay > 0) p.fanDelay -= dt;

        /* Stick to the enemy this shot was fired at. Re-picking `nearestEnemy`
           every frame is what made `targets > 1` a no-op: the siblings are born
           at the same point, so they all resolved to the SAME nearest enemy and
           the other targets were never hit.

           `gen` is the guard, not `hp > 0` — enemies come from a Pool, so a
           dead one is recycled into a different creature with full hp. Charmed
           ones are dropped too: the collision loop skips them, so homing at one
           is a shot that can never land. */
        let target = p.target;
        if (target && (target.gen !== p.targetGen || target.hp <= 0 || target.charmed)) {
          target = p.target = null;
        }
        if (!target) {
          target = this.nearestEnemy(p.x, p.y, 900);
          if (target) { p.target = target; p.targetGen = target.gen; }
        }

        if (target && p.fanDelay <= 0) {
          const desired = Math.atan2(target.y - p.y, target.x - p.x);
          const cur = Math.atan2(p.vy, p.vx);
          let diff = desired - cur;
          while (diff > Math.PI) diff -= Math.PI * 2;
          while (diff < -Math.PI) diff += Math.PI * 2;
          const turn = Math.max(-p.turnRate * dt, Math.min(p.turnRate * dt, diff));
          const a = cur + turn;
          p.vx = Math.cos(a) * p.speed;
          p.vy = Math.sin(a) * p.speed;
        }
      }

      p.update(dt);
      if (!p.dead && p.hostile) {
        const dx = pl.x - p.x, dy = pl.y - p.y, rr = pl.radius + p.radius;
        if (dx * dx + dy * dy < rr * rr) {
          this.damagePlayer(p.damage, "projectile");
          p.dead = true;
          // longe de quem atirou. Dano de contato (`touch`) fica de fora do
          // stop de proposito: ele cobra por sub-step enquanto houver encosto,
          // e um congelamento por cobranca faria o jogo arrastar.
          this.addShake(7, pl.x - p.x, pl.y - p.y);
          this.addHitstop(BALANCE.camera.hitstop.hurt);
          this.sfx.hurt();
          this.spawnParticles(pl.x, pl.y, "#ff5a5f", 8);
        }
      } else if (!p.dead) {
        this.grid.forNear(p.x, p.y, (e) => {
          if (p.dead || e.hp <= 0 || e.charmed) return;
          const dx = e.x - p.x, dy = e.y - p.y;
          const rr = e.radius + p.radius;
          if (dx * dx + dy * dy < rr * rr) {
            if (p.hits) { if (p.hits.has(e)) return; p.hits.add(e); }
            const dealt = this.damageEnemy(e, p.damage, p.source);
            /* Som so em acerto DISCRETO. Tique de DoT e de zona cobram por
               sub-step enquanto durarem — um estalo por cobranca viraria
               metralhadora exatamente quando a horda fecha. E a mesma regra
               que mantem o dano continuo fora do hitstop. */
            this.emitSfx("hit", e.x, e.y, 0.2);
            if (p.payload) {
              const c = pushCtx(this);
              c.key = p.source; c.color = p.color; c.now = this.clock;
              c.x = e.x; c.y = e.y; c.target = e; c.amount = dealt;
              c.dirX = p.vx; c.dirY = p.vy;
              runEffects(this, p.payload, c);
              popCtx(this);
            }
            /* A piercing shot RELEASES its target on the way through. The
               spawn-time target exists so sibling shots leave at different
               enemies; keeping it for the whole flight is what killed the
               chaining — re-seeking after each pierce is precisely what carries
               a shot through the pack, and pinning it cost 37% of the damage of
               the 7-shot tier. Measured, not guessed. */
            if (p.pierce > 0) { p.pierce--; p.target = null; }
            else p.dead = true;
          }
        });
      }
    }
    this.projectiles.sweep(DEAD);
  }

  updateAreas(dt) {
    const list = this.areas.active;
    const p = this.player;
    const n = list.length;
    for (let i = 0; i < n; i++) {
      const a = list[i];
      if (a.dead) continue;
      if (a.follow) { a.x = p.x; a.y = p.y; }
      a.life -= dt;
      a.tickTimer -= dt;
      if (a.tickTimer <= 0) {
        a.tickTimer += a.tickInterval;
        const dmg = a.dps * a.tickInterval;
        this.grid.forRadius(a.x, a.y, a.radius, (e) => {
          if (e.hp <= 0 || e.charmed) return;
          const dx = e.x - a.x, dy = e.y - a.y, rr = a.radius + e.radius;
          if (dx * dx + dy * dy > rr * rr) return;
          const dealt = dmg > 0 ? this.damageEnemy(e, dmg, a.source) : 0;
          if (a.payload) {
            const c = pushCtx(this);
            c.key = a.source; c.color = a.color; c.now = this.clock;
            c.x = e.x; c.y = e.y; c.target = e; c.amount = dealt;
            c.dirX = p.dirX; c.dirY = p.dirY;
            runEffects(this, a.payload, c);
            popCtx(this);
          }
        });
      }
      if (a.life <= 0) {
        if (a.onEnd) {
          const c = pushCtx(this);
          c.key = a.source; c.color = a.color; c.now = this.clock;
          c.x = a.x; c.y = a.y; c.target = null;
          c.dirX = p.dirX; c.dirY = p.dirY;
          runEffects(this, a.onEnd, c);
          popCtx(this);
        }
        a.dead = true;
      }
    }
    this.areas.sweep(DEAD);
  }

  /* Idem: o evento de morte acorda Colheita, Seed of Corruption e afins, que
     causam dano e podem matar mais inimigos no meio da varredura. */
  killDeadEnemies() {
    const list = this.enemies.active;
    const n = list.length;
    for (let i = 0; i < n; i++) {
      const e = list[i];
      if (e.hp > 0 || e.dead) continue;

      // emitido ANTES de limpar os DoTs: Colheita e Seed of Corruption
      // dependem de conseguir ler o que o morto carregava.
      if (!e.noReward) this.events.emit(EVENTS.ENEMY_KILLED, { enemy: e });
      this.dots.clear(e);

      if (!e.noReward) {
        this.orbs.spawn(e.x, e.y, e.type.xp);
        // corpo maior = som mais grave; o timbre vem do dado do inimigo
        const heft = e.type.boss ? 1 : clamp((e.radius - 12) / 26, 0, 1);
        this.shatterEnemy(e, heft);
        this.sfx.death(heft, e.type.deathSfx);
        this.onReapKill();
        this.onComboKill();
        if (e.type.boss) this.bossAlive = Math.max(0, this.bossAlive - 1);
        if (e.type.boss) {
          this.addShake(13, e.x - this.player.x, e.y - this.player.y);
          this.addHitstop(BALANCE.camera.hitstop.boss, true);
        }
        this.player.kills++;
        this.dropLoot(e);
        if (e.type.deathBlast) this.deathBlast(e);
      }
      e.noReward = false;
      e.dead = true;
    }
    this.enemies.sweep(DEAD);
  }

  /* Inimigo que cobra ao MORRER. E dado (`type.deathBlast`), nao um if com o id
     do sapador dentro: qualquer casta futura declara o campo e ganha o mesmo
     comportamento.

     Duas coisas nao obvias moram aqui. O estouro NAO chama damageEnemy — se
     chamasse, um sapador matando o vizinho dispararia o estouro dele no meio
     da varredura de `killDeadEnemies`, que e exatamente o laco que cresce
     enquanto e percorrido. Ele so cobra do JOGADOR, que e onde a ameaca esta.
     E o hitstop e o tremor entram pela cadencia normal, sem `force`: numa
     leva inteira explodindo junto, um stop por corpo viraria apresentacao de
     slides. */
  /* `falloff` e a fracao cobrada na BORDA, e ele existe porque o estouro chato
     nao dava ao jogador nada para decidir. O unico input do jogo e movimento e
     toda peca dispara sozinha: quem escolhe MATAR o sapador de longe e a build,
     nao o jogador. Entao um estouro que cobra o mesmo encostado e a 85 unidades
     nao pune "deixei a horda chegar" — ele so taxa a horda chegar, que e o que
     a densidade deste jogo garante que aconteca.

     Com falloff a conta volta a depender de ONDE o jogador estava, que e a
     unica variavel que ele controla. Medido (`driver_autopsy`, 8 runs, mesmas
     seeds): a rajada de 2s cai de 100% da barra na pior run para 40%, o
     sapador sai de 96% do dano tomado para 60% — continua sendo a maior
     ameaca, deixa de ser o jogo inteiro — e as mortes antes dos 3 min caem de
     5/8 para 1/8. Sem `falloff` no dado, o comportamento e o de antes. */
  deathBlast(e) {
    const b = e.type.deathBlast;
    this.emitVfx("burst", e.x, e.y, b.radius, e.type.color);
    this.spawnParticles(e.x, e.y, e.type.color, 10);
    const dx = this.player.x - e.x, dy = this.player.y - e.y;
    const reach = b.radius + this.player.radius;
    const d2 = dx * dx + dy * dy;
    if (d2 > reach * reach) return;
    const edge = b.falloff != null ? b.falloff : 1;
    const near = 1 - Math.sqrt(d2) / reach;   // 1 no centro, 0 na borda
    this.damagePlayer(e.blastDamage * (edge + (1 - edge) * near), "blast");
    this.addShake(9, -dx, -dy);
    this.addHitstop(BALANCE.camera.hitstop.hurt);
  }

  // Um único ponto de entrada para o baú: o boss larga o dele, o spawner solta
  // os avulsos, e os dois passam pelo mesmo aviso de que há prêmio no chão.
  spawnChestAt(x, y) {
    this.pickups.spawn(x, y, "chest");
    this.spawnParticles(x, y, ITEMS.chest.color, 14);
    this.emitVfx("summon", x, y, 44, ITEMS.chest.color);
  }

  dropLoot(e) {
    if (e.type.boss) {
      if (this.elapsed - this.lastBossChestAt >= BALANCE.spawn.bossChestCooldown) {
        this.lastBossChestAt = this.elapsed;
        this.spawnChestAt(e.x, e.y);
      } else {
        for (let k = 0; k < 6; k++) {
          const a = (Math.PI * 2 / 6) * k;
          this.orbs.spawn(e.x + Math.cos(a) * 26, e.y + Math.sin(a) * 26, e.type.xp);
        }
      }
      return;
    }
    for (const id in ITEMS) {
      if (ITEMS[id].dropChance > 0 && Math.random() < ITEMS[id].dropChance) {
        this.pickups.spawn(e.x, e.y, id);
        break;
      }
    }
  }

  updateOrbs(dt) {
    const list = this.orbs.active;
    for (let i = 0; i < list.length; i++) {
      if (list[i].update(dt, this.player)) {
        this.player.gainXp(list[i].value);
        this.orbs.release(i); i--;
      }
    }
  }

  updatePickups(dt) {
    const list = this.pickups.active, p = this.player;
    for (let i = 0; i < list.length; i++) {
      const pk = list[i];
      pk.bob += dt * 4;
      const dx = p.x - pk.x, dy = p.y - pk.y, rr = p.radius + 14;
      if (dx * dx + dy * dy < rr * rr) {
        pk.item.onPickup(this);
        if (!pk.item.silent) {
          this.sfx.item();
          this.addShake(4);
          this.ui.toast({ name: pk.item.name });
        }
        this.pickups.release(i); i--;
        // Dois baús no mesmo frame: o segundo openChest sobrescreveria a tela
        // do primeiro. O que sobrou fica no chão para o frame seguinte.
        if (this.state !== STATE.PLAYING) break;
      }
    }
  }

  updateParticles(dt) {
    const list = this.particles.active;
    for (let i = 0; i < list.length; i++) {
      if (list[i].update(dt)) { this.particles.release(i); i--; }
    }
  }

  openChest() { this.ui.openChest(); }

  /* --- render: a ordem das chamadas E a ordem de profundidade -------------- */
  render() {
    const ctx = this.wctx;
    const cam = this.camera, now = this.clock;
    const fdt = this._frameDt || 1 / 60;
    const t = (this._vfxClock = (this._vfxClock || 0) + fdt);

    if (this.state === STATE.MENU) {
      // o menu roda o mesmo cenário, andando devagar de lado
      this.camera.x += 14 * fdt;
      this.scenery.draw(ctx, cam, t);
      this.scenery.drawEmbers(ctx, cam, t, fdt);
      this.scenery.drawAtmosphere(ctx, cam);
      this.present();
      return;
    }
    this.scenery.draw(ctx, cam, t);

    // O residuo E o chao por um tempo: ele vem logo depois dele e antes de
    // qualquer entidade. Evento acontece SOBRE o mundo; chamusco acontece NELE.
    this.vfxLayer.drawDecals(ctx, cam);

    const areas = this.areas.active;
    for (let i = 0; i < areas.length; i++) areas[i].draw(ctx, cam);

    drawPieceOverlays(ctx, this.build, this.player, cam);

    const orbs = this.orbs.active;
    for (let i = 0; i < orbs.length; i++) orbs[i].draw(ctx, cam);

    const pickups = this.pickups.active;
    for (let i = 0; i < pickups.length; i++) pickups[i].draw(ctx, cam);

    const enemies = this.enemies.active;
    for (let i = 0; i < enemies.length; i++) enemies[i].draw(ctx, cam, now);

    drawMinions(ctx, this.minions.active, cam, now);

    const parts = this.particles.active;
    for (let i = 0; i < parts.length; i++) parts[i].draw(ctx, cam);

    this.player.draw(ctx, cam, this.build.vfx);

    const proj = this.projectiles.active;
    for (let i = 0; i < proj.length; i++) proj[i].draw(ctx, cam);

    this.vfxLayer.draw(ctx, cam);

    // no ar, acima do mundo e abaixo da HUD
    this.scenery.drawEmbers(ctx, cam, t, fdt);
    this.scenery.drawAtmosphere(ctx, cam);

    this.present();
  }
}

window.addEventListener("DOMContentLoaded", () => { window.game = new Game(); });
