"use strict";
/* =========================================================================
   MOVIMENTO E CONTROLE — o que compra espaco.
   Nao matam; decidem onde a horda pode estar. Numa build em que a unica
   decisao em tempo real e posicionamento, isso e dano indireto.
   ========================================================================= */

Object.assign(PIECES, {

  burningRush: {
    id: "burningRush", key: "burningRush", name: "Burning Rush",
    color: "#ff8a3c", axis: "cataclysm", axisPoints: 1,
    tags: ["speed", "aura"],
    desc: "Corre muito mais rápido queimando a própria vida — a queima nunca chega a te matar.",
    stats: { interval: 0.5, speedMul: 1.35, drain: 0.55, radius: 0 },
    trigger: { type: "aura", interval: "@interval" },
    effects: [
      { type: "self_speed", factor: "@speedMul", duration: 0.7 },
      { type: "self_damage", amount: "@drain" },
    ],
    paths: {
      speed: { name: "Velocidade", tiers: [
        T("Passada", "+8% de velocidade.", { speedMul: { add: 0.08 } }),
        T("Disparada", "+10% de velocidade.", { speedMul: { add: 0.1 } }),
        T("Sprint", "+14% de velocidade.", { speedMul: { add: 0.14 } }),
        T("Vento Fel", "+16% de velocidade.", { speedMul: { add: 0.16 } }),
        T("Velocidade do Vazio", "+25% de velocidade.", { speedMul: { add: 0.25 } }),
      ]},
      cost: { name: "Custo", tiers: [
        T("Economia", "-30% de vida queimada.", { drain: { mul: 0.7 } }),
        T("Fôlego", "-30% de vida queimada.", { drain: { mul: 0.7 } }),
        T("Sopro", "-40% de vida queimada.", { drain: { mul: 0.6 } }),
        T("Adaptação", "Cura 6 por pulso enquanto corre.", null,
          { "effects.2": { type: "heal", amount: 6 } }),
        T("Sem Custo", "A corrida deixa de queimar vida.", { drain: { set: 0 } }),
      ]},
      wake: { name: "Esteira", tiers: [
        T("Chamuscar", "Deixa fogo por onde passa.", null,
          { "effects.3": { type: "area_persistent", radius: 60, dps: 22,
                           duration: 2, tickInterval: 0.4, color: "#ff8a3c" } }),
        T("Brasa", "+80% de dano da esteira.", null, { "effects.3.dps": 40 }),
        T("Trilha Larga", "+50% de raio da esteira.", null, { "effects.3.radius": 90 }),
        T("Persistente", "A esteira dura 4s.", null, { "effects.3.duration": 4 }),
        T("Cometa", "A esteira empurra e triplica de dano.", null,
          { "effects.3.dps": 120,
            "effects.4": { type: "knockback", force: 40, radius: 90 } }),
      ]},
    },
  },

  demonicCircle: {
    id: "demonicCircle", key: "demonicCircle", name: "Demonic Circle",
    color: "#9a4cff", axis: "dominion", axisPoints: 1,
    tags: ["escape", "aura"],
    desc: "Se a horda te cercar, você simplesmente não está mais lá.",
    stats: { interval: 1, minEnemies: 7, checkRadius: 130, distance: 240 },
    trigger: { type: "aura", interval: "@interval" },
    effects: [
      { type: "hook", name: "blink", minEnemies: "@minEnemies",
        checkRadius: "@checkRadius", distance: "@distance" },
    ],
    paths: {
      escape: { name: "Fuga", tiers: [
        T("Reflexo", "Dispara com 5 inimigos em volta.", { minEnemies: { set: 5 } }),
        T("Salto Longo", "+40% de distância.", { distance: { mul: 1.4 } }),
        T("Pânico", "Dispara com 3 inimigos em volta.", { minEnemies: { set: 3 } }),
        T("Salto Duplo", "+50% de distância.", { distance: { mul: 1.5 } }),
        T("Fuga Constante", "Checa 3x mais rápido.", { interval: { mul: 0.33 } }),
      ]},
      exit: { name: "Saída", tiers: [
        T("Estouro", "Deixa uma explosão no ponto de saída.", null,
          { "effects.1": { type: "damage_instant", amount: 70, radius: 140, big: true } }),
        T("Onda", "+80% de dano da explosão.", null, { "effects.1.amount": 130 }),
        T("Repulsa", "A saída empurra tudo.", null,
          { "effects.2": { type: "knockback", force: 140, radius: 160 } }),
        T("Pausa", "A saída atordoa por 1s.", null,
          { "effects.3": { type: "stun", duration: 1, radius: 160 } }),
        T("Colapso", "O dano da saída triplica.", null, { "effects.1.amount": 400 }),
      ]},
      arrival: { name: "Chegada", tiers: [
        T("Escudo", "Ganha 50 de escudo ao saltar.", null,
          { "effects.4": { type: "shield", amount: 50, cap: 220 } }),
        T("Reforço", "O escudo sobe para 110.", null, { "effects.4.amount": 110 }),
        T("Terror", "Amedronta quem estava em volta por 2s.", null,
          { "effects.5": { type: "fear", duration: 2, radius: 180 } }),
        T("Vitalidade", "Cura 30 ao saltar.", null,
          { "effects.6": { type: "heal", amount: 30 } }),
        T("Portal de Guerra", "Invoca 3 caçadores na chegada.", null,
          { "effects.7": { type: "summon", kind: "dreadstalker", ai: "chase",
                           count: 3, cap: 12, duration: 10, damage: 30 },
            "effects.8": { type: "vfx", kind: "portal", radius: 26 } }),
      ]},
    },
  },

  shadowfury: {
    id: "shadowfury", key: "shadowfury", name: "Shadowfury",
    color: "#e0521a", axis: "cataclysm", axisPoints: 1,
    tags: ["control", "aura"],
    desc: "Um pulso que congela a horda no lugar. Compra o segundo que faltava.",
    stats: { interval: 6, radius: 190, duration: 1.2, damage: 30 },
    trigger: { type: "aura", interval: "@interval" },
    effects: [
      { type: "stun", duration: "@duration", radius: "@radius" },
      { type: "damage_instant", amount: "@damage", radius: "@radius" },
    ],
    paths: {
      hold: { name: "Trava", tiers: [
        T("Fixação", "+50% de duração do atordoamento.", { duration: { mul: 1.5 } }),
        T("Cadência", "Pulsa 30% mais rápido.", { interval: { mul: 0.7 } }),
        T("Paralisia", "Dobra a duração.", { duration: { mul: 2 } }),
        T("Constância", "Pulsa 40% mais rápido.", { interval: { mul: 0.6 } }),
        T("Tempo Parado", "Atordoa até os chefes.", null, { "effects.0.affectsBoss": true }),
      ]},
      reach: { name: "Amplitude", tiers: [
        T("Expansão", "+35% de raio.", { radius: { mul: 1.35 } }),
        T("Onda", "+35% de raio.", { radius: { mul: 1.35 } }),
        T("Domo", "+45% de raio.", { radius: { mul: 1.45 } }),
        T("Repulsa", "O pulso também empurra.", null,
          { "effects.2": { type: "knockback", force: 110, radius: "@radius" } }),
        T("Horizonte", "Dobra o raio.", { radius: { mul: 2 } }),
      ]},
      fury: { name: "Fúria", tiers: [
        T("Impacto", "+70% de dano.", { damage: { mul: 1.7 } }),
        T("Estrondo", "Dobra o dano.", { damage: { mul: 2 } }),
        T("Fratura", "Alvos atordoados ficam lentos por 3s.", null,
          { "effects.3": { type: "slow", factor: 0.5, duration: 3, radius: "@radius" } }),
        T("Devastação", "Dobra o dano de novo.", { damage: { mul: 2 } }),
        T("Cataclismo", "O pulso vira um golpe grande e triplica de dano.",
          { damage: { mul: 3 } }, { "effects.1.big": true }),
      ]},
    },
  },

  curseOfExhaustion: {
    id: "curseOfExhaustion", key: "curseOfExhaustion", name: "Curse of Exhaustion",
    color: "#4a9e2e", axis: "corruption", axisPoints: 1,
    tags: ["control", "aura"],
    desc: "Uma aura de cansaço. A horda continua vindo — só que devagar.",
    stats: { interval: 0.6, radius: 210, factor: 0.65, duration: 1.4 },
    trigger: { type: "aura", interval: "@interval" },
    effects: [
      { type: "slow", factor: "@factor", duration: "@duration", radius: "@radius" },
    ],
    paths: {
      weight: { name: "Peso", tiers: [
        T("Cansaço", "-10% na velocidade dos afetados.", { factor: { add: -0.1 } }),
        T("Fadiga", "-10% na velocidade.", { factor: { add: -0.1 } }),
        T("Exaustão", "-12% na velocidade.", { factor: { add: -0.12 } }),
        T("Chumbo", "-12% na velocidade.", { factor: { add: -0.12 } }),
        T("Estase", "Reduz a velocidade a um quinto.", { factor: { set: 0.2 } }),
      ]},
      reach: { name: "Alcance", tiers: [
        T("Expansão", "+30% de raio.", { radius: { mul: 1.3 } }),
        T("Amplitude", "+30% de raio.", { radius: { mul: 1.3 } }),
        T("Maré", "+40% de raio.", { radius: { mul: 1.4 } }),
        T("Persistência", "+2s de duração da lentidão.", { duration: { add: 2 } }),
        T("Horizonte", "Dobra o raio.", { radius: { mul: 2 } }),
      ]},
      decay: { name: "Definhar", tiers: [
        T("Corrosão", "A aura também causa dano.", null,
          { "effects.1": { type: "damage_instant", amount: 8, radius: "@radius" } }),
        T("Erosão", "+90% de dano.", null, { "effects.1.amount": 15 }),
        T("Apodrecimento", "A aura aplica um DoT.", null,
          { "effects.2": { type: "damage_over_time", key: "exhaust", dps: 8,
            duration: 4, tickInterval: 0.6, color: "#4a9e2e", radius: "@radius" } }),
        T("Definhar", "+80% do DoT.", null, { "effects.2.dps": 15 }),
        T("Colapso", "Dano e DoT triplicam.", null,
          { "effects.1.amount": 45, "effects.2.dps": 45 }),
      ]},
    },
  },

  curseOfTongues: {
    id: "curseOfTongues", key: "curseOfTongues", name: "Curse of Tongues",
    color: "#4a9e2e", axis: "corruption", axisPoints: 1,
    tags: ["control", "aura"],
    desc: "A horda gagueja. Bate mais devagar e machuca menos.",
    stats: { interval: 0.8, radius: 220, factor: 0.6, duration: 2 },
    trigger: { type: "aura", interval: "@interval" },
    effects: [
      { type: "weaken", factor: "@factor", duration: "@duration", radius: "@radius" },
    ],
    paths: {
      silence: { name: "Silêncio", tiers: [
        T("Gagueira", "-10% no dano dos afetados.", { factor: { add: -0.1 } }),
        T("Balbucio", "-10% no dano.", { factor: { add: -0.1 } }),
        T("Mudez", "-12% no dano.", { factor: { add: -0.12 } }),
        T("Afasia", "-12% no dano.", { factor: { add: -0.12 } }),
        T("Silêncio Absoluto", "Reduz o dano deles a um quinto.", { factor: { set: 0.2 } }),
      ]},
      reach: { name: "Alcance", tiers: [
        T("Expansão", "+30% de raio.", { radius: { mul: 1.3 } }),
        T("Amplitude", "+35% de raio.", { radius: { mul: 1.35 } }),
        T("Persistência", "+2s de duração.", { duration: { add: 2 } }),
        T("Maré", "+45% de raio.", { radius: { mul: 1.45 } }),
        T("Horizonte", "Dobra o raio.", { radius: { mul: 2 } }),
      ]},
      dread: { name: "Pavor", tiers: [
        T("Hesitação", "A aura também deixa lento.", null,
          { "effects.1": { type: "slow", factor: 0.7, duration: "@duration", radius: "@radius" } }),
        T("Tremor", "A lentidão fica mais forte.", null, { "effects.1.factor": 0.5 }),
        T("Terror", "A cada pulso, amedronta por 1s.", null,
          { "effects.2": { type: "fear", duration: 1, radius: "@radius" } }),
        T("Pânico", "O medo dura 2s.", null, { "effects.2.duration": 2 }),
        T("Loucura", "O medo passa a afetar até chefes.", null,
          { "effects.2.affectsBoss": true }),
      ]},
    },
  },

  howlOfTerror: {
    id: "howlOfTerror", key: "howlOfTerror", name: "Howl of Terror",
    color: "#6a28c8", axis: "dominion", axisPoints: 1,
    tags: ["control", "reactive"],
    desc: "Quando encostam em você, o grito espalha a horda. Resposta, não prevenção.",
    stats: { radius: 200, duration: 2.2, cooldown: 4 },
    trigger: { type: "reactive", event: "player_damaged", cooldown: "@cooldown", atPlayer: true },
    effects: [
      { type: "fear", duration: "@duration", radius: "@radius" },
    ],
    paths: {
      terror: { name: "Terror", tiers: [
        T("Pavor", "+50% de duração do medo.", { duration: { mul: 1.5 } }),
        T("Reflexo", "Dispara 30% mais rápido.", { cooldown: { mul: 0.7 } }),
        T("Horror", "Dobra a duração.", { duration: { mul: 2 } }),
        T("Prontidão", "Dispara 40% mais rápido.", { cooldown: { mul: 0.6 } }),
        T("Loucura", "O medo afeta até chefes.", null, { "effects.0.affectsBoss": true }),
      ]},
      reach: { name: "Alcance", tiers: [
        T("Eco", "+35% de raio.", { radius: { mul: 1.35 } }),
        T("Ressonância", "+35% de raio.", { radius: { mul: 1.35 } }),
        T("Onda", "O grito também empurra.", null,
          { "effects.1": { type: "knockback", force: 130, radius: "@radius" } }),
        T("Amplitude", "+45% de raio.", { radius: { mul: 1.45 } }),
        T("Horizonte", "Dobra o raio.", { radius: { mul: 2 } }),
      ]},
      lash: { name: "Revide", tiers: [
        T("Estilhaço", "O grito causa dano em área.", null,
          { "effects.2": { type: "damage_instant", amount: 60, radius: "@radius" } }),
        T("Estrondo", "+90% de dano.", null, { "effects.2.amount": 115 }),
        T("Casca", "Ganha 45 de escudo ao gritar.", null,
          { "effects.3": { type: "shield", amount: 45, cap: 240 } }),
        T("Reforço", "O escudo sobe para 100.", null, { "effects.3.amount": 100 }),
        T("Grito de Ruína", "O dano triplica e vira golpe grande.", null,
          { "effects.2.amount": 350, "effects.2.big": true }),
      ]},
    },
  },

  mortalCoil: {
    id: "mortalCoil", key: "mortalCoil", name: "Mortal Coil",
    color: "#4a9e2e", axis: "corruption", axisPoints: 1,
    tags: ["control", "heal", "reactive"],
    desc: "Em vida baixa, empurra a horda e devolve fôlego. O botão de pânico automático.",
    stats: { threshold: 0.4, radius: 190, force: 170, heal: 0.2, cooldown: 9 },
    trigger: { type: "reactive", event: "player_damaged", condition: "player_below",
               pct: "@threshold", cooldown: "@cooldown", atPlayer: true },
    effects: [
      { type: "knockback", force: "@force", radius: "@radius" },
      { type: "hook", name: "healthstone", threshold: 1, frac: "@heal" },
    ],
    paths: {
      coil: { name: "Espiral", tiers: [
        T("Empurrão", "+50% de força.", { force: { mul: 1.5 } }),
        T("Amplitude", "+35% de raio.", { radius: { mul: 1.35 } }),
        T("Repulsa", "Dobra a força.", { force: { mul: 2 } }),
        T("Onda", "+50% de raio.", { radius: { mul: 1.5 } }),
        T("Vórtice", "O empurrão também atordoa por 1.5s.", null,
          { "effects.2": { type: "stun", duration: 1.5, radius: "@radius" } }),
      ]},
      mend: { name: "Restauro", tiers: [
        T("Fôlego", "+50% de cura.", { heal: { mul: 1.5 } }),
        T("Recarga", "Dispara 30% mais rápido.", { cooldown: { mul: 0.7 } }),
        T("Vitalidade", "Dobra a cura.", { heal: { mul: 2 } }),
        T("Alerta", "Dispara já abaixo de 55% de vida.", { threshold: { set: 0.55 } }),
        T("Renascer", "Cura 80% da vida máxima.", { heal: { set: 0.8 } }),
      ]},
      lash: { name: "Revide", tiers: [
        T("Terror", "Também amedronta por 2s.", null,
          { "effects.3": { type: "fear", duration: 2, radius: "@radius" } }),
        T("Estilhaço", "Também causa dano em área.", null,
          { "effects.4": { type: "damage_instant", amount: 90, radius: "@radius" } }),
        T("Estrondo", "+90% de dano.", null, { "effects.4.amount": 170 }),
        T("Casca", "Ganha 90 de escudo.", null,
          { "effects.5": { type: "shield", amount: 90, cap: 300 } }),
        T("Ceifa", "O dano executa alvos abaixo de 35%.", null,
          { "effects.6": { type: "execute", threshold: 0.35, amount: 90,
                           executeMul: 6, radius: "@radius" } }),
      ]},
    },
  },

  banish: {
    id: "banish", key: "banish", name: "Banish",
    color: "#6a28c8", axis: "dominion", axisPoints: 1,
    tags: ["control"],
    desc: "Tira o maior problema do tabuleiro por alguns segundos.",
    stats: { cooldown: 7, range: 460, duration: 5, targets: 1 },
    trigger: { type: "auto_target", cooldown: "@cooldown", range: "@range", targets: "@targets" },
    effects: [
      { type: "stun", duration: "@duration", affectsBoss: true },
    ],
    paths: {
      bind: { name: "Grilhão", tiers: [
        T("Corrente", "+40% de duração.", { duration: { mul: 1.4 } }),
        T("Recarga", "Recarrega 30% mais rápido.", { cooldown: { mul: 0.7 } }),
        T("Selo", "Dobra a duração.", { duration: { mul: 2 } }),
        T("Prontidão", "Recarrega 40% mais rápido.", { cooldown: { mul: 0.6 } }),
        T("Exílio", "Triplica a duração.", { duration: { mul: 3 } }),
      ]},
      reach: { name: "Alcance", tiers: [
        T("Dois Alvos", "Bane 2 alvos.", { targets: { set: 2 } }),
        T("Longo Braço", "+40% de alcance.", { range: { mul: 1.4 } }),
        T("Quatro Alvos", "Bane 4 alvos.", { targets: { set: 4 } }),
        T("Amplitude", "+50% de alcance.", { range: { mul: 1.5 } }),
        T("Expurgo", "Bane todos num raio de 200.", null, { "effects.0.radius": 200 }),
      ]},
      punish: { name: "Punição", tiers: [
        T("Marca", "O banido sofre +40% de dano.", null,
          { "effects.1": { type: "mark", amp: 0.4, duration: "@duration" } }),
        T("Sentença", "A marca sobe para +80%.", null, { "effects.1.amp": 0.8 }),
        T("Corrosão", "O banido também recebe um DoT pesado.", null,
          { "effects.2": { type: "damage_over_time", key: "banish", dps: 30,
            duration: "@duration", tickInterval: 0.5, color: "#6a28c8" } }),
        T("Suplício", "+100% do DoT.", null, { "effects.2.dps": 60 }),
        T("Execução", "Ao acabar, o banido leva um golpe massivo.", null,
          { "effects.2.onExpire.0": { type: "damage_instant", amount: 600,
            radius: 130, big: true } }),
      ]},
    },
  },

  enslaveDemon: {
    id: "enslaveDemon", key: "enslaveDemon", name: "Enslave Demon",
    color: "#9a4cff", axis: "dominion", axisPoints: 1,
    tags: ["control", "summon"],
    desc: "Vira um inimigo contra os próprios. O exército cresce roubando peça.",
    stats: { cooldown: 8, range: 300, duration: 10 },
    trigger: { type: "auto_target", cooldown: "@cooldown", range: "@range", targets: 1 },
    effects: [
      { type: "convert", duration: "@duration" },
    ],
    paths: {
      bond: { name: "Vínculo", tiers: [
        T("Coleira", "+40% de duração.", { duration: { mul: 1.4 } }),
        T("Recarga", "Recarrega 30% mais rápido.", { cooldown: { mul: 0.7 } }),
        T("Servidão", "Dobra a duração.", { duration: { mul: 2 } }),
        T("Prontidão", "Recarrega 40% mais rápido.", { cooldown: { mul: 0.6 } }),
        T("Escravidão Eterna", "O convertido nunca volta atrás.", { duration: { mul: 6 } }),
      ]},
      reach: { name: "Alcance", tiers: [
        T("Longo Braço", "+40% de alcance.", { range: { mul: 1.4 } }),
        T("Rede", "+40% de alcance.", { range: { mul: 1.4 } }),
        T("Cerco", "Recarrega 35% mais rápido.", { cooldown: { mul: 0.65 } }),
        T("Amplitude", "+50% de alcance.", { range: { mul: 1.5 } }),
        T("Chamado", "Converte todos num raio de 160.", null, { "effects.0.radius": 160 }),
      ]},
      spoils: { name: "Espólio", tiers: [
        T("Tributo", "A conversão te dá 40 de escudo.", null,
          { "effects.1": { type: "shield", amount: 40, cap: 220 } }),
        T("Saque", "O escudo sobe para 90.", null, { "effects.1.amount": 90 }),
        T("Sangue", "A conversão cura 30.", null,
          { "effects.2": { type: "heal", amount: 30 } }),
        T("Legião", "A conversão também invoca 2 imps.", null,
          { "effects.3": { type: "summon", kind: "imp", ai: "chase", count: 2,
                           cap: 16, duration: 12, damage: 24 } }),
        T("Recrutamento", "Invoca 4 caçadores por conversão.", null,
          { "effects.3.kind": "dreadstalker", "effects.3.count": 4,
            "effects.3.damage": 45 }),
      ]},
    },
  },

});
