"use strict";
/* =========================================================================
   MATILHA — o eixo que escala com o NÚMERO DE BICHOS VIVOS.

   Consequência de desenho: quase toda peça daqui ou põe um bicho em campo ou
   paga por haver bichos em campo. Uma peça de Matilha que não olhe para a
   população está no eixo errado — ela seria uma peça de Precisão pintada de
   ouro.

   Cor: `AXIS_PALETTE.pack` — base #e0b833, light #f5d45c, deep #9c7a12.
   ========================================================================= */

Object.assign(PIECES, {

  /* O kit inicial do hunter. Mira sozinha, não pede nada do jogador e não
     semeia eixo nenhum além do próprio — é a mesma função que o Incinerate tem
     no warlock: a primeira etapa continua sendo descoberta, não confirmação. */
  killCommand: {
    id: "killCommand", cls: "hunter", key: "killCommand", name: "Kill Command",
    color: "#e0b833", axis: "pack", axisPoints: 2,
    tags: ["beast", "strike", "command"], vfx: "thorn",
    desc: "Mira sozinha o inimigo mais próximo e manda a matilha estraçalhá-lo: dano direto que cresce com quantos bichos você tem vivos.",
    stats: { cooldown: 1.5, range: 420, damage: 120, radius: 46, perBeast: 26, targets: 1 },
    trigger: { type: "auto_target", cooldown: "@cooldown", range: "@range", targets: "@targets" },
    effects: [
      { type: "damage_instant", amount: "@damage", radius: "@radius", atTarget: true,
        shape: "rip", color: "#e0b833" },
      { type: "hook", name: "comandoDaMatilha", amount: "@perBeast", link: true },
    ],
    paths: {
      command: { name: "Comando", evolvesInto: "howlOfThePackLeader", tiers: [
        T("Ordem", "+45% de dano.", { damage: { mul: 1.45 } }),
        T("Grito", "Comanda 30% mais rápido.", { cooldown: { mul: 0.7 } }),
        T("Sangue", "Dobra o dano.", { damage: { mul: 2 } }),
        T("Coro", "Comanda dois alvos por vez.", { targets: { add: 1 } }),
        T("Estraçalhar", "Triplica o dano.", { damage: { mul: 3 } }),
      ]},
      bond: { name: "Vínculo", tiers: [
        T("Elo", "+60% do bônus por bicho vivo.", { perBeast: { mul: 1.6 } }),
        T("Matilha Unida", "+60% do bônus por bicho vivo de novo.", { perBeast: { mul: 1.6 } }),
        T("Fome", "O golpe também faz sangrar.", null,
          { "effects.3": { type: "damage_over_time", key: "killCommand",
            dps: "@damage*0.25", duration: 4, tickInterval: 0.5, atTarget: true,
            look: "rot", color: "#9c7a12" } }),
        T("Faro", "+50% de alcance.", { range: { mul: 1.5 } }),
        T("Alcateia", "Triplica o bônus por bicho vivo.", { perBeast: { mul: 3 } }),
      ]},
      rend: { name: "Dilaceração", tiers: [
        T("Rasgo", "+40% de raio do golpe.", { radius: { mul: 1.4 } }),
        T("Estilhaço", "O golpe empurra o resto para longe.", null,
          { "effects.5": { type: "knockback", force: 80, radius: "@radius" } }),
        T("Presa Longa", "+50% de raio.", { radius: { mul: 1.5 } }),
        T("Golpe Fundo", "O alvo passa a receber 30% mais dano por 4s.", null,
          { "effects.6": { type: "mark", amp: 0.3, duration: 4, atTarget: true } }),
        T("Esquartejar", "Dobra o raio.", { radius: { mul: 2 } }),
      ]},
    },
  },

  barbedShot: {
    id: "barbedShot", cls: "hunter", key: "barbedShot", name: "Barbed Shot",
    color: "#9c7a12", axis: "pack", axisPoints: 2,
    tags: ["beast", "dot", "shot"], vfx: "rot",
    desc: "Mira sozinha e crava um farpado que sangra o alvo — e o cheiro de sangue deixa toda a sua matilha mais rápida enquanto dura.",
    stats: { cooldown: 2.6, range: 460, damage: 60, dotDps: 70, dotTime: 6,
             tickInterval: 0.5, speedMul: 0.35, duration: 5 },
    trigger: { type: "auto_target", cooldown: "@cooldown", range: "@range" },
    effects: [
      { type: "projectile", damage: "@damage", speed: 620, radius: 5, trail: 150,
        homing: true, turnRate: 5, color: "#9c7a12",
        onHit: [
          { type: "damage_over_time", key: "barbedShot", dps: "@dotDps",
            duration: "@dotTime", tickInterval: "@tickInterval",
            look: "unstable", color: "#9c7a12" },
        ] },
      { type: "hook", name: "farejarSangue", frac: "@speedMul", duration: "@duration" },
    ],
    paths: {
      barb: { name: "Farpa", tiers: [
        T("Ponta", "+50% do dano do sangramento.", { dotDps: { mul: 1.5 } }),
        T("Retorcida", "O sangramento dura +3s.", { dotTime: { add: 3 } }),
        T("Serrilhada", "Dobra o dano do sangramento.", { dotDps: { mul: 2 } }),
        T("Tica Rápido", "O sangramento tica 40% mais rápido.", { tickInterval: { mul: 0.6 } }),
        T("Dilacerar", "Triplica o dano do sangramento.", { dotDps: { mul: 3 } }),
      ]},
      frenzy: { name: "Frenesi", tiers: [
        T("Cheiro", "+50% da aceleração da matilha.", { speedMul: { mul: 1.5 } }),
        T("Persiste", "A aceleração dura +4s.", { duration: { add: 4 } }),
        T("Sede", "+60% da aceleração de novo.", { speedMul: { mul: 1.6 } }),
        T("Cadência", "Crava 30% mais rápido.", { cooldown: { mul: 0.7 } }),
        T("Alucinação", "Dobra a aceleração.", { speedMul: { mul: 2 } }),
      ]},
      spread: { name: "Contágio", tiers: [
        T("Salpico", "O sangramento salta para um vizinho.", null,
          { "effects.0.onHit.5": { type: "chain", range: 160, falloff: 0.7,
            effects: [{ type: "damage_over_time", key: "barbedShot", dps: "@dotDps*0.6",
              duration: "@dotTime", tickInterval: "@tickInterval", look: "unstable",
              color: "#9c7a12" }] } }),
        T("Alcance", "O salto vai 60 unidades mais longe.", { range: { add: 60 } }),
        T("Poça", "Quem morre sangrando espalha o sangramento.", null,
          { "effects.0.onHit.6": { type: "spread_on_death", radius: 120, maxTargets: 3 } }),
        T("Impacto", "+70% do dano de impacto.", { damage: { mul: 1.7 } }),
        T("Epidemia", "O salto perde muito menos força.", null,
          { "effects.0.onHit.5": { type: "chain", range: 220, falloff: 1,
            effects: [{ type: "damage_over_time", key: "barbedShot", dps: "@dotDps",
              duration: "@dotTime", tickInterval: "@tickInterval", look: "unstable",
              color: "#9c7a12" }] } }),
      ]},
    },
  },

  beastCleave: {
    id: "beastCleave", cls: "hunter", key: "beastCleave", name: "Beast Cleave",
    color: "#f5d45c", axis: "pack", axisPoints: 2,
    tags: ["beast", "area", "reactive"],
    requires: { tag: "beast" },
    desc: "Sempre que um bicho seu morde, o golpe abre em leque em volta dele e pega tudo que estiver encostado.",
    stats: { cooldown: 0.25, damage: 78, radius: 96, bleed: 22 },
    trigger: { type: "reactive", event: "minion_hit", cooldown: "@cooldown" },
    effects: [
      { type: "damage_instant", amount: "@damage", radius: "@radius", atTarget: true,
        shape: "nova", color: "#f5d45c" },
      { type: "damage_over_time", key: "beastCleave", dps: "@bleed", duration: 3,
        tickInterval: 0.5, radius: "@radius", atTarget: true,
        look: "rot", color: "#9c7a12" },
    ],
    paths: {
      arc: { name: "Arco", tiers: [
        T("Leque", "+40% de raio.", { radius: { mul: 1.4 } }),
        T("Meia-lua", "+50% de dano.", { damage: { mul: 1.5 } }),
        T("Círculo", "+50% de raio.", { radius: { mul: 1.5 } }),
        T("Talho", "Dobra o dano.", { damage: { mul: 2 } }),
        T("Ceifa", "Dobra o raio.", { radius: { mul: 2 } }),
      ]},
      echo: { name: "Eco", tiers: [
        T("Repique", "Abre 40% mais vezes.", { cooldown: { mul: 0.6 } }),
        T("Segundo Talho", "Um segundo leque, mais fraco, logo atrás.", null,
          { "effects.2": { type: "damage_instant", amount: "@damage*0.5",
            radius: "@radius*0.7", atTarget: true, shape: "nova", color: "#f5d45c" } }),
        T("Sem Fôlego", "Abre quase o dobro de vezes.", { cooldown: { mul: 0.5 } }),
        T("Onda", "O leque empurra tudo para fora.", null,
          { "effects.3": { type: "knockback", force: 70, radius: "@radius", atTarget: true } }),
        T("Furacão", "Triplica o dano.", { damage: { mul: 3 } }),
      ]},
      maul: { name: "Maul", tiers: [
        T("Corte", "+80% do dano do sangramento.", { bleed: { mul: 1.8 } }),
        T("Fundo", "+60% de dano.", { damage: { mul: 1.6 } }),
        T("Tendão", "O leque deixa quem pega mais lento.", null,
          { "effects.5": { type: "slow", factor: 0.6, duration: 2, radius: "@radius",
            atTarget: true } }),
        T("Osso", "+70% de raio.", { radius: { mul: 1.7 } }),
        T("Carniça", "Dobra o dano e o raio.", { damage: { mul: 2 }, radius: { mul: 2 } }),
      ]},
    },
  },

  wildThrash: {
    id: "wildThrash", cls: "hunter", key: "wildThrash", name: "Wild Thrash",
    color: "#e0b833", axis: "pack", axisPoints: 2,
    tags: ["beast", "pack", "melee"],
    desc: "Mantém uma matilha de lobos caçando sozinha: eles cercam o alvo por lados diferentes e cada mordida abre em área.",
    stats: {
      count: 3, interval: 7, damage: 92, blast: 62, blastRadius: 72,
      duration: 16, speed: 320, attackInterval: 0.7,
    },
    trigger: { type: "pack", count: "@count", interval: "@interval", litter: "@count" },
    effects: [
      { type: "summon", kind: "wolf", ai: "flank", count: 1, cap: "@count",
        damage: "@damage", duration: "@duration", speed: "@speed",
        attackInterval: "@attackInterval",
        onHit: [{ type: "damage_instant", amount: "@blast", radius: "@blastRadius" }] },
    ],
    paths: {
      fang: { name: "Presa", tiers: [
        T("Mordida", "+45% de dano da mordida.", { damage: { mul: 1.45 } }),
        T("Dilacerar", "+50% do dano em área da mordida.", { blast: { mul: 1.5 } }),
        T("Rasgo", "A mordida faz sangrar.", null,
          { "effects.0.onHit.2": { type: "damage_over_time", key: "wildThrash",
            dps: "@damage*0.3", duration: 4, tickInterval: 0.5, look: "rot", color: "#9c7a12" } }),
        T("Presa Longa", "+60% de raio da área.", { blastRadius: { mul: 1.6 } }),
        T("Esquartejar", "Triplica o dano da mordida.", { damage: { mul: 3 } }),
      ]},
      pack: { name: "Alcateia", tiers: [
        T("Par", "Mais um lobo na matilha.", { count: { add: 1 } }),
        T("Fôlego", "Os lobos duram +8s.", { duration: { add: 8 } }),
        T("Trio", "Mais dois lobos na matilha.", { count: { add: 2 } }),
        T("Reposição", "A matilha se repõe 40% mais rápido.", { interval: { mul: 0.6 } }),
        T("Matilha", "Mais três lobos na matilha.", { count: { add: 3 } }),
      ]},
      hunt: { name: "Caçada", tiers: [
        T("Faro", "Os lobos correm 25% mais rápido.", { speed: { mul: 1.25 } }),
        T("Investida", "Mordem 30% mais rápido.", { attackInterval: { mul: 0.7 } }),
        T("Acuar", "A mordida deixa o alvo mais lento.", null,
          { "effects.0.onHit.4": { type: "slow", factor: 0.55, duration: 2 } }),
        T("Perseguir", "Correm mais 30%.", { speed: { mul: 1.3 } }),
        T("Frenesi", "Mordem quase o dobro de rápido.", { attackInterval: { mul: 0.55 } }),
      ]},
    },
  },

  callOfTheWild: {
    id: "callOfTheWild", cls: "hunter", key: "direBeast", name: "Call of the Wild",
    color: "#f5d45c", axis: "pack", axisPoints: 0,
    tags: ["beast", "pack", "summon"], evolutionOnly: true, vfx: "sigil",
    desc: "Chama uma leva de javalis que entra inteira de uma vez, investe e some — reforço temporário, não matilha permanente.",
    stats: { count: 4, interval: 11, damage: 84, duration: 7, speed: 355, attackInterval: 0.9 },
    trigger: { type: "pack", count: "@count", interval: "@interval", litter: "@count" },
    effects: [
      { type: "summon", kind: "boar", ai: "flank", count: 1, cap: "@count",
        damage: "@damage", duration: "@duration", speed: "@speed",
        attackInterval: "@attackInterval",
        onHit: [{ type: "knockback", force: 60 }] },
    ],
    paths: {
      wild: { name: "Vara", tiers: [
        T("Dois a Mais", "Mais dois javalis na leva.", { count: { add: 2 } }),
        T("Demoram", "A leva dura +4s.", { duration: { add: 4 } }),
        T("Três a Mais", "Mais três javalis na leva.", { count: { add: 3 } }),
        T("Volta Logo", "A leva volta 35% mais rápido.", { interval: { mul: 0.65 } }),
        T("Debandada", "Mais cinco javalis na leva.", { count: { add: 5 } }),
      ]},
      might: { name: "Investida", tiers: [
        T("Chifre", "+50% de dano.", { damage: { mul: 1.5 } }),
        T("Atropelo", "A investida abre em área.", null,
          { "effects.0.onHit.2": { type: "damage_instant", amount: "@damage*0.6", radius: 80 } }),
        T("Tromba", "Correm 30% mais rápido.", { speed: { mul: 1.3 } }),
        T("Presa de Osso", "Dobra o dano.", { damage: { mul: 2 } }),
        T("Estouro da Boiada", "A investida atordoa por 0.7s.", null,
          { "effects.0.onHit.3": { type: "stun", duration: 0.7, radius: 80 } }),
      ]},
      roam: { name: "Chamado", tiers: [
        T("Berro", "Investem 25% mais rápido.", { attackInterval: { mul: 0.75 } }),
        T("Corno", "+40% de dano.", { damage: { mul: 1.4 } }),
        T("Trompa", "Investem mais 30% rápido.", { attackInterval: { mul: 0.7 } }),
        T("Fôlego Longo", "A leva dura +6s.", { duration: { add: 6 } }),
        T("Chamado da Selva", "Um urso vem junto com a leva.", null,
          { "effects.2": { type: "summon", kind: "bear", ai: "anchor", count: 1, cap: 1,
            damage: "@damage*1.6", duration: "@duration", attackInterval: 1.1,
            onHit: [{ type: "knockback", force: 110, radius: 90 }] } }),
      ]},
    },
  },

  direBeast: {
    id: "direBeast", cls: "hunter", key: "direBeast", name: "Dire Beast",
    color: "#e0b833", axis: "pack", axisPoints: 2,
    tags: ["beast", "summon"],
    desc: "Chama sozinha, de tempos em tempos, um bicho grande da mata — nunca se sabe qual vem, e ele caça sozinho até a hora dele acabar.",
    stats: { count: 1, interval: 6, damage: 130, duration: 12, speed: 300, attackInterval: 0.9 },
    trigger: { type: "autonomous", count: "@count", interval: "@interval" },
    effects: [
      { type: "hook", name: "bichoDaMata", damage: "@damage", duration: "@duration",
        speed: "@speed", attackInterval: "@attackInterval", cap: "@count" },
    ],
    paths: {
      wild: { name: "Matilha", evolvesInto: "callOfTheWild", tiers: [
        T("Mais Um", "Mais um bicho ao mesmo tempo.", { count: { add: 1 } }),
        T("Demora", "Os bichos duram +6s.", { duration: { add: 6 } }),
        T("Mais Dois", "Mais dois bichos ao mesmo tempo.", { count: { add: 2 } }),
        T("Chamado Curto", "Chama 35% mais rápido.", { interval: { mul: 0.65 } }),
        T("Mata Fechada", "Mais três bichos ao mesmo tempo.", { count: { add: 3 } }),
      ]},
      might: { name: "Porte", tiers: [
        T("Grande", "+50% de dano.", { damage: { mul: 1.5 } }),
        T("Feroz", "Atacam 25% mais rápido.", { attackInterval: { mul: 0.75 } }),
        T("Colossal", "Dobra o dano.", { damage: { mul: 2 } }),
        T("Veloz", "Correm 35% mais rápido.", { speed: { mul: 1.35 } }),
        T("Lendário", "Triplica o dano.", { damage: { mul: 3 } }),
      ]},
      roam: { name: "Território", tiers: [
        T("Persistente", "Os bichos duram +8s.", { duration: { add: 8 } }),
        T("Presa Fácil", "O golpe deles deixa o alvo mais lento.", null,
          { "effects.2": { type: "hook", name: "bichoDaMata", damage: "@damage",
            duration: "@duration", speed: "@speed", attackInterval: "@attackInterval",
            cap: "@count", slow: 0.6 } }),
        T("Fôlego", "Os bichos duram +12s.", { duration: { add: 12 } }),
        T("Rota Longa", "Chama 30% mais rápido.", { interval: { mul: 0.7 } }),
        T("Reserva", "Os bichos duram +20s.", { duration: { add: 20 } }),
      ]},
    },
  },

  stampede: {
    id: "stampede", cls: "hunter", key: "stampede", name: "Stampede",
    color: "#9c7a12", axis: "pack", axisPoints: 2,
    tags: ["beast", "line", "charge"], vfx: "meteor",
    desc: "Enquanto você anda, uma correria de bichos atravessa o chão à sua frente e atropela tudo na linha.",
    stats: { cooldown: 2.2, distance: 130, damage: 190, radius: 104, force: 90 },
    trigger: { type: "directional", cooldown: "@cooldown", distance: "@distance" },
    effects: [
      { type: "damage_instant", amount: "@damage", radius: "@radius", big: true,
        shape: "rip", color: "#9c7a12" },
      { type: "knockback", force: "@force", radius: "@radius" },
    ],
    paths: {
      trample: { name: "Atropelo", tiers: [
        T("Casco", "+50% de dano.", { damage: { mul: 1.5 } }),
        T("Peso", "+40% de empurrão.", { force: { mul: 1.4 } }),
        T("Manada", "Dobra o dano.", { damage: { mul: 2 } }),
        T("Rolo Compressor", "A correria atordoa por 0.8s.", null,
          { "effects.3": { type: "stun", duration: 0.8, radius: "@radius" } }),
        T("Debandada", "Triplica o dano.", { damage: { mul: 3 } }),
      ]},
      lane: { name: "Corredor", tiers: [
        T("Largo", "+35% de raio.", { radius: { mul: 1.35 } }),
        T("Longe", "Passa 70 unidades mais à frente.", { distance: { add: 70 } }),
        T("Mais Largo", "+50% de raio.", { radius: { mul: 1.5 } }),
        T("Cadência", "Passa 35% mais vezes.", { cooldown: { mul: 0.65 } }),
        T("Avenida", "Dobra o raio.", { radius: { mul: 2 } }),
      ]},
      dust: { name: "Poeira", tiers: [
        T("Rastro", "A correria deixa poeira que fere quem fica.", null,
          { "effects.5": { type: "area_persistent", radius: "@radius*0.8",
            dps: "@damage*0.25", duration: 3, tickInterval: 0.4, look: "ash",
            color: "#9c7a12" } }),
        T("Densa", "+60% do dano da poeira.", { damage: { mul: 1.6 } }),
        T("Cega", "A poeira deixa quem está nela mais lento.", null,
          { "effects.5.onTick.0": { type: "slow", factor: 0.6, duration: 1.5 } }),
        T("Assenta Devagar", "A poeira dura +3s.", null,
          { "effects.5.duration": 6 }),
        T("Tempestade", "Dobra o dano.", { damage: { mul: 2 } }),
      ]},
    },
  },

  howlOfThePackLeader: {
    id: "howlOfThePackLeader", cls: "hunter", key: "killCommand",
    name: "Howl of the Pack Leader",
    color: "#f5d45c", axis: "pack", axisPoints: 0,
    tags: ["beast", "summon", "reactive"], evolutionOnly: true, vfx: "sigil",
    requires: { tag: "beast" },
    desc: "Quando você toma dano, o uivo responde: um bicho grande da matilha entra em campo do seu lado e caça até acabar.",
    stats: { cooldown: 7, damage: 210, duration: 13, attackInterval: 0.95, count: 1 },
    trigger: { type: "reactive", event: "player_damaged", cooldown: "@cooldown", atPlayer: true },
    effects: [
      { type: "summon", kind: "wyvern", ai: "ranged", count: "@count", cap: 3,
        damage: "@damage", duration: "@duration", attackInterval: "@attackInterval",
        projectile: { damage: "@damage", speed: 560, radius: 5, trail: 120, color: "#f5d45c" } },
    ],
    paths: {
      command: { name: "Resposta", tiers: [
        T("Ecoa", "Responde 30% mais rápido.", { cooldown: { mul: 0.7 } }),
        T("Alto", "+50% de dano do bicho.", { damage: { mul: 1.5 } }),
        T("Dois Vêm", "Vêm dois bichos por uivo.", { count: { add: 1 } }),
        T("Longo", "Os bichos duram +8s.", { duration: { add: 8 } }),
        T("Coro", "Vêm três bichos por uivo.", { count: { add: 1 } }),
      ]},
      bond: { name: "Javali", tiers: [
        T("Vem Junto", "Um javali entra junto do uivo.", null,
          { "effects.2": { type: "summon", kind: "boar", ai: "flank", count: 1, cap: 4,
            damage: "@damage*0.7", duration: "@duration", attackInterval: 0.9,
            onHit: [{ type: "knockback", force: 70 }] } }),
        T("Dois Javalis", "Dois javalis por uivo.", null,
          { "effects.2.count": 2 }),
        T("Presas", "+60% de dano.", { damage: { mul: 1.6 } }),
        T("Couro Duro", "Os bichos duram +6s.", { duration: { add: 6 } }),
        T("Vara Inteira", "Quatro javalis por uivo.", null,
          { "effects.2.count": 4 }),
      ]},
      rend: { name: "Urso", tiers: [
        T("Vem o Urso", "Um urso entra junto e fica ao seu lado.", null,
          { "effects.4": { type: "summon", kind: "bear", ai: "anchor", count: 1, cap: 2,
            damage: "@damage*1.3", duration: "@duration", attackInterval: 1.1,
            onHit: [{ type: "damage_instant", amount: "@damage*0.5", radius: 90 }] } }),
        T("Patada", "+50% de dano.", { damage: { mul: 1.5 } }),
        T("Rugido", "A patada do urso atordoa por 0.6s.", null,
          { "effects.4.onHit.1": { type: "stun", duration: 0.6, radius: 90 } }),
        T("Dois Ursos", "Dois ursos por uivo.", null,
          { "effects.4.count": 2 }),
        T("Guardião", "Os ursos duram +15s.", { duration: { add: 15 } }),
      ]},
    },
  },

  bestialWrath: {
    id: "bestialWrath", cls: "hunter", key: "bestialWrath", name: "Bestial Wrath",
    color: "#e0b833", axis: "pack", axisPoints: 2,
    tags: ["beast", "aura", "buff"], vfx: "blood",
    requires: { tag: "beast" },
    desc: "Aura constante em volta de você: fere quem chega perto e deixa a sua matilha em fúria enquanto o pulso durar.",
    stats: { interval: 1.1, damage: 96, radius: 168, speedMul: 0.3, duration: 2.4 },
    trigger: { type: "aura", interval: "@interval" },
    effects: [
      { type: "damage_instant", amount: "@damage", radius: "@radius",
        shape: "nova", color: "#e0b833" },
      { type: "hook", name: "farejarSangue", frac: "@speedMul", duration: "@duration" },
    ],
    paths: {
      rage: { name: "Fúria", tiers: [
        T("Rosnado", "+50% de dano.", { damage: { mul: 1.5 } }),
        T("Sanha", "Pulsa 30% mais rápido.", { interval: { mul: 0.7 } }),
        T("Fera", "Dobra o dano.", { damage: { mul: 2 } }),
        T("Ódio", "+60% da fúria da matilha.", { speedMul: { mul: 1.6 } }),
        T("Selvageria", "Triplica o dano.", { damage: { mul: 3 } }),
      ]},
      reach: { name: "Presença", tiers: [
        T("Território", "+35% de raio.", { radius: { mul: 1.35 } }),
        T("Domínio", "+40% de raio.", { radius: { mul: 1.4 } }),
        T("Cerco", "O pulso deixa quem pega mais lento.", null,
          { "effects.3": { type: "slow", factor: 0.65, duration: 1.6, radius: "@radius" } }),
        T("Reserva", "+50% de raio.", { radius: { mul: 1.5 } }),
        T("Selva", "Dobra o raio.", { radius: { mul: 2 } }),
      ]},
      feast: { name: "Banquete", tiers: [
        T("Sangue", "O pulso faz sangrar.", null,
          { "effects.5": { type: "damage_over_time", key: "bestialWrath",
            dps: "@damage*0.2", duration: 4, tickInterval: 0.5, radius: "@radius",
            look: "rot", color: "#9c7a12" } }),
        T("Fome", "A fúria da matilha dura +2s.", { duration: { add: 2 } }),
        T("Voracidade", "+70% de dano.", { damage: { mul: 1.7 } }),
        T("Carniça", "O pulso também empurra.", null,
          { "effects.6": { type: "knockback", force: 60, radius: "@radius" } }),
        T("Festim", "Dobra a fúria da matilha.", { speedMul: { mul: 2 } }),
      ]},
    },
  },

  animalCompanion: {
    id: "animalCompanion", cls: "hunter", key: "animalCompanion", name: "Animal Companion",
    color: "#f5d45c", axis: "pack", axisPoints: 2,
    tags: ["beast", "summon", "anchor"],
    desc: "Mantém um urso permanente andando ao seu lado: ele investe em quem chega perto de VOCÊ, não em quem está mais perto dele.",
    stats: { count: 1, interval: 5, damage: 165, duration: 24, attackInterval: 1.1,
             blast: 84, blastRadius: 92, shield: 34 },
    trigger: { type: "autonomous", count: "@count", interval: "@interval" },
    effects: [
      { type: "summon", kind: "bear", ai: "anchor", count: 1, cap: "@count",
        damage: "@damage", duration: "@duration", attackInterval: "@attackInterval",
        onHit: [{ type: "damage_instant", amount: "@blast", radius: "@blastRadius" }] },
    ],
    paths: {
      loyal: { name: "Lealdade", tiers: [
        T("Fiel", "O urso dura +10s.", { duration: { add: 10 } }),
        T("Companheiro", "Mais um urso ao seu lado.", { count: { add: 1 } }),
        T("Inseparável", "O urso dura +20s.", { duration: { add: 20 } }),
        T("Volta Logo", "Reaparece 40% mais rápido.", { interval: { mul: 0.6 } }),
        T("Para Sempre", "O urso dura muito mais.", { duration: { mul: 4 } }),
      ]},
      claw: { name: "Garra", tiers: [
        T("Patada", "+45% de dano.", { damage: { mul: 1.45 } }),
        T("Golpe Largo", "+50% do dano em área.", { blast: { mul: 1.5 } }),
        T("Rasgo", "Ataca 25% mais rápido.", { attackInterval: { mul: 0.75 } }),
        T("Talho", "Dobra o dano.", { damage: { mul: 2 } }),
        T("Devastar", "A patada atordoa por 0.7s.", null,
          { "effects.0.onHit.2": { type: "stun", duration: 0.7, radius: "@blastRadius" } }),
      ]},
      guard: { name: "Guarda", tiers: [
        T("Escudo Vivo", "Cada patada do urso te devolve casca.", null,
          { "effects.0.onHit.4": { type: "shield", amount: "@shield" } }),
        T("Couraça", "+80% da casca por patada.", { shield: { mul: 1.8 } }),
        T("Presença", "+60% de raio do golpe em área.", { blastRadius: { mul: 1.6 } }),
        T("Rugido", "O golpe empurra tudo para fora.", null,
          { "effects.0.onHit.3": { type: "knockback", force: 100, radius: "@blastRadius" } }),
        T("Muralha", "Dobra a casca por patada.", { shield: { mul: 2 } }),
      ]},
    },
  },

});
