"use strict";
/* =========================================================================
   TILES — as oito lajes do chão, desenhadas à mão a partir de referência.

   O chão era gerado por código (`makeFelTile` sorteava granulado, juntas e
   veios). Isto aqui é o mesmo chão como DADO: uma grade de 42x42 por laje,
   nos tokens da PAL, do mesmo tamanho em que ela aparece — `BALANCE.world.tile`
   (126) dividido por `PIXEL_UNIT` (3). Nada é reescalado no blit.

   Three rules paid for in the conversion, and each is visible the moment it is
   broken:

   1. A tile is seen forty times on one screen, so it may carry STRUCTURE and
      never a BLOTCH. Each slab was high-passed before being quantised: what
      survives is the joint, the crack and the grain, and what dies is how light
      the reference happened to paint that face. A lighter face kept its value
      and came back as a lit pad stamped across the floor.
   2. A slab carrying a mark — a fel vein, a rune — is singular, so it is RARE.
      `TILE_BAG` weights the plain ones five to one; picking uniformly put a
      rune on one cell in eight and the eye found the lattice immediately.
   3. Eight stamps still repeat. Mirroring is free (integer flip, no resampling,
      so the pixel grid is untouched) and turns eight slabs into thirty-two.

   O vocabulário de char é o mesmo dos sprites: `o` contorno, `d`/`m`/`l` a
   rampa, `e`/`E` energia. A laje é matéria — o verde e a runa juntos ficam em
   0,8% dos pixels, bem abaixo do teto de 14% da regra de corpo aceso.
   ========================================================================= */

const TILE_SIZE = 42;

const TILE_PAL = {
  o: PAL.inkDeep,   // junta e fenda
  d: PAL.vio0,      // a massa da laje
  m: PAL.vio1,      // lábio erguido da junta
  l: PAL.stone0,    // grão gasto, raro
  e: PAL.fel0,      // veio de fel
  E: PAL.fel1,      // núcleo do veio
  f: PAL.arc0,      // a runa gravada
};

const TILE_ROWS = [
  [
    "oooooooddddmmmmmmmmmmmmmmmmmmmmddddoodddoo",
    "ollmmmddddddoooooooooooooooooooodddddmmmoo",
    "olddodddddooooooooooooooooooooddddddddmmoo",
    "omddddddddddddooooooooooodddddddddddddmmoo",
    "omooodddddddddddddddddddddddddddddddddmmoo",
    "ddddddddddddddddddddddddddddddddddddddmmoo",
    "ddddddddddddddddddddddddddddddddddddddmmoo",
    "ddodddddddddddddddddddddddddddddddddddmmoo",
    "ddodddddddddddddddddddddddddddddddddddmmoo",
    "moodddddddddodddddddddddddddddddddddddmmoo",
    "moodddddddodddddddddddddddddddddddddddmmoo",
    "moooddddddddddddddddddddddddddddddddddmmoo",
    "mooddddddddddddddddddddddddddddddddddddmoo",
    "moddddddddddddddddddddddddddddddddddddddoo",
    "modddddddddddddddddddddddddddddddddddddmoo",
    "moddddddddddddddddddddddddddddddddddddddoo",
    "moodddddddddddddddddddddddddddddddddddddoo",
    "moddddddddddddddddddddddddddddddddddddddoo",
    "moddddddddddddddddddddddddddddddddddddddoo",
    "moodddddddddddddddddddddddddddddddddddddoo",
    "mdodddddddddddddddddddddddddddddddddddddoo",
    "ddddddddddddddddddddddddddddddddddddddddoo",
    "ddddddddddddddddddddddddddddddddddddddddoo",
    "odddddddddddddddddddddddddddddddddddddddoo",
    "omddddddddddddddddddddddddddddddddddddddoo",
    "omddddddddddddddddddddddddddddddddddddddoo",
    "omddddddddddddddddddddddddddddddddddddddoo",
    "omddddddddddddddddddddddddddddddddddddddoo",
    "omddddddddddddddddddddddddddddddddddddddoo",
    "omdddddddddddddddddddddddddddoodddddddddoo",
    "omddddddddddddddddddddddddddooddddddddddoo",
    "omddddddddddddddddddddddddddodddddddddddoo",
    "omddddddddddddddddddddddddddddddddddddddoo",
    "omddddddddddddddddddddddddddddddddddddddoo",
    "omdddddddddddddddddddddddddddddddddddddmoo",
    "omdddddddddddddddddddddddddddddddddddddmoo",
    "omddddddddddddddddddddddddddddddddddddmmoo",
    "omddddddddddddddddddddddddddddddddddddmmoo",
    "oldddddddddddddddddddddddddddddddddmmmmmoo",
    "oldddddddddddddddddddddddddddddmmmmmmmmdoo",
    "omooodddddddddddddddddoooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooooo",
  ],
  [
    "oddddddddddddddddmldoomlmmmmmmmdoommmmmmmo",
    "omdddddddddddddddmmoooldooooodddoodddddddo",
    "dddddddddddddddddmmooomddooooddddodddddddo",
    "dddddddodddddddddmmdoomddooodddddomddddddo",
    "dddddddddddddddddmmdoomdddddddddddoddddddo",
    "dddddddddddddddddmmdoomdddddddddddoddddddo",
    "dddddodddddddddddmmdooldddddddddddoodddddo",
    "dddddddddddddddddmmdooldddddddddddooddddmo",
    "ddddddddddddddddddmdooldddddddddddddoooddo",
    "dddddddddddddddddmmdoomddddddddddodddddodo",
    "dddddddddddddddddmmdoomdddddddddodddddddoo",
    "dddddddddddddddddmmdoodddddddddddddddddddo",
    "dddddddddddddddddmmdoodddddddddddddddddddo",
    "dddddddddddddddoodmdoodddddddddddddddddddo",
    "dddddddddddddddoddmmoodddddddddddddddddddo",
    "oddddddddddddddddmmmoodddddddddddddddddddo",
    "dddddddddddddddddmmmoommddddddddddddddmmdo",
    "dmmmmmmmmmmmmmmmmllmoommmddddddddddmmmmmdo",
    "dmmmmmmmmmmmmmmmmlldoolmmdddddddddddddmmoo",
    "oooooooooooooooooooooodooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooooo",
    "ommllmollllllllllllmoolllmmddddmmlllllllmo",
    "lmddddoddddddddddmmdoolddddddddddddddddddo",
    "mddddddoddddddddddmdoolddddddddddddddddddo",
    "mooddddoodddddooddddoomdoodddddddoooooddoo",
    "mdddddddooddddddddddoomdddddoddddddddddddo",
    "dddddddddoodddddddddoomddddddddddddddddddo",
    "oddddddddddoddddddddoomddddddddddddddddddo",
    "ooooddddooooodddddmdoomddddddddddddddddddo",
    "omddddoodddddooddmmdoomddddddddddddddddddo",
    "mdddddddddddddoodmmdoolddddddddddddddddddo",
    "mddddddddddddddooooooolddddddddddddddddddo",
    "moodddddddddddddddddoomddodddddddddddddddo",
    "moodddddddddddddddmmoomddodddddddddddddddo",
    "moodddddddddddddddmmoomddodddddddddddddddo",
    "moddddddddddddddddmdoolddodddddddddddddddo",
    "moodddddddddddddddmdoolddodddddddddddddddo",
    "moddddddddddddddddmdoolddodddddddddddddddo",
    "mddddddddddddddddmmdoolddddddddddddddddddo",
    "mmdddddddddddddddmmdoolddddddddddddddddddo",
    "ddoddddddddddddddddoooldddddddddddddddddoo",
    "oooooooooooooooooooooooooooooooooooooooooo",
  ],
  [
    "ooooooooddddmmmmommmmmmmmmmmmmmddddoodddoo",
    "ollmmmmddddddddooddooooooooooooodddddmmmoo",
    "olddoddddddddddomdddooooooooodddddddddmmoo",
    "omdddddddddddddoddddddddddddddddddddddmmoo",
    "omooodddddddddooddddddddddddddddddddddmmoo",
    "oddddddddddddddoodddddddddddddddddddddmmoo",
    "ddddddddddddddddoooddddddddddddddddddddmoo",
    "dddddddddddddddddooddddddddddddddddddddmoo",
    "ddoddddddddddddddddddddddddddddddddddddmoo",
    "mdodddddddddddddddddddddddddddddddddddmmoo",
    "mooddddddddddddddomdddddddddddddddddddmmoo",
    "mooodddddddddddddomdddddddddddddddddddmmoo",
    "mooodddddddddddddodddddddddddddddddddddooo",
    "mooodddddddddddddodddddddddddddddddddoomdo",
    "mooodddddddddddddodddddddddddddddddooommoo",
    "moodddddddddddddddooodddddddddddddooddmmdo",
    "moddddddddddddddddddoddddddddddoooddddmmoo",
    "moddddddddddddddddddddddddddoooodddddddmoo",
    "mooddddddddddddddddddddddoooodddddddddddoo",
    "mooodddddddddddddddddddooodmddddddddddddoo",
    "ddddddddddddddddddddddooldddddddddddddddoo",
    "ddddddddddddddddddddddodddddddddddddddddoo",
    "ddddddddddddddddddddddomddddddddddddddddoo",
    "oddddddddddddddddddddoodddddddddddddddddoo",
    "omdddddddddddddddddddoodddddddddddddddddoo",
    "omdddddddddddddddddddoddddddddddddddddddoo",
    "omddddddddddddddddddoomdddddddddddddddddoo",
    "omddddddddddddddddddomddddddddddddddddddoo",
    "omdddddddddddddddddoodddddddddddddddddddoo",
    "omdddddddddddddddddomdddddddddddddddddddoo",
    "omddddddddddddddddomddddddddddddddddddddoo",
    "omdddddddddddddddoddddddddddddddddddddddoo",
    "omddddddddddddddooddddddddddddddddddddddoo",
    "omdddddddddddddoodddddddddddddddddddddddoo",
    "omdddddddddddooomddddddddddddddddddddddmoo",
    "omdddddddddddodmdddddddddddddddddddddddmoo",
    "omddddddddddodmdddddddddddddddddddddddmmoo",
    "omdddddddddoomddddddddddddddddddddddddmmoo",
    "olddddddmmmomddddddddddddddddddddddmmmmmoo",
    "oldddddmmmoolmddddddddddddddddmmmmmmmmmdoo",
    "omooodddmoodmmdddddddddooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooooo",
  ],
  [
    "oooddddddddddddddmldoollmmmmmmmmmmddddmmdo",
    "omdddddddddddddddmmoodmdooooooooooddddddoo",
    "dddddddddddddddddmmoodmdooooooooddddddddoo",
    "ddddoddddddddddddmmoodmddooodddddddddddddo",
    "dddddddffdddoddddmmoodmddddddddddddddddddo",
    "dddddddfffddfddddmmooomddddddddddddddddddo",
    "dddddddfdffdofdddmmooomddddddddddddddddddo",
    "dddddddfddffdddddmmdoomddddddddooddddddddo",
    "dddddddfdddfdddddmmdoolddddddddddmdddddddo",
    "oddddddfddffdddddmmdoolddddddddddddddddddo",
    "oddddddfdffddddddmmdoolddddddddddddddddddo",
    "omdddddffddddddddmmdoolddddddddddddddddddo",
    "odddddofddofoddddmmdoomddddddddddddddddddo",
    "dddddddfddddfddddmlooooddddddddddddddddddo",
    "dddooddoddddfdddddoooddddddddddddddddddddo",
    "dddddddoddddddddoomdodmdmddddddddddddddddo",
    "ddddddddddddddoodmmdodmddddddddddddddddddo",
    "mdddddddddmmmddmmmldodmmdoddddddddddddmmdo",
    "mmmmmmmmmmmmmdlmmlldodmmmddmmmmdmdmmmmmmdo",
    "mmmmmmmmmmmmommmlllooommdddoddddddddddmdoo",
    "oooooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooooo",
    "dlmmmmmmmllllmdmmlldoolllllmmmmmmmllllllmo",
    "ldddddddddddddoddmmoodlmddddddddddddddmmdo",
    "mddddddddddddddodmmoodlddddddddddddddddmdo",
    "mooodddddoodddddodddoomddoddddddddddddddoo",
    "moodddddddddddddddddoomddddddddddddddddddo",
    "moddddddddddddddddooodmddddddddddddddddddo",
    "modddddddddddddddddooddddddddddddddddddddo",
    "mdddddddddddoddddddooddddddddddddddddddddo",
    "dddddddddoddoddddddoomdddddddddddddddddddo",
    "odddddoddddddddddddoomddddddmddddddddddddo",
    "oddddddodddddddddddoommddddddddddddddddddo",
    "oodddddddddddddddddoodmddddddddddddddddddo",
    "odooddddddddddddddmdoomddddddddddddddddddo",
    "dddoodddddddddddddmdoomddddddddddddddddddo",
    "ddddddddddddddddddmdoomdddddddddddddoddddo",
    "ddddddddddddddddddmdoolddddddddddddddddddo",
    "mddddddddddddddddmmdoolmddddddddddddddmmdo",
    "mddddddooddddddddmmooolmddddddddddddddmmdo",
    "mddddddddodddddddmmooolmddddddddddddddmdoo",
    "oooooooooooooooooooooooooooooooooooooooooo",
  ],
  [
    "odmmmmllmoommddmmmmmmmmmmmmlloommddooodooo",
    "olddoodddomddddddooooooooodddomdddddmmlmoo",
    "dmoooodddodddooooooooooooodddoddddddddmmoo",
    "ddoooddddoddddddoddoooodddddooddddddddmmoo",
    "ddddddddodddddddddddddddddddddoddddddddmoo",
    "ddddddddodddddddddddddddddddddodddddddmmoo",
    "oddddddoodddddddddddddddddddddoddddddddmoo",
    "ooooooddodddddddddddddddddodddoddddddddmoo",
    "oddddddddoddddddddddddddddoddooooddddddmoo",
    "mdddddddddoddddddddddddddoooodddoodddddmoo",
    "mdddddddddddddddddddddddooddddddddoooddmoo",
    "moddddddddddddddddddddddodddddddddddddmooo",
    "moddddddddddooodddddddddddddddddddddddmmoo",
    "mooddddddddddddodddddddddddddddddddddddmoo",
    "modddddddddddddooddddddddddddddddddddddmoo",
    "mododdddddddddddoddddoddddddddddddddddddoo",
    "dodddddddddddddddoododddddddddddddddddddoo",
    "moodddddddddddddodddodddddddddddddddddddoo",
    "mooddddddddddddddddoodddddddddddddddddddoo",
    "mooodddddddddddddddoddddodddddddddddddddoo",
    "mooodddddddddddddddoddddddddddddddddddddoo",
    "mooodddddddddddomdodddddddddddddddddddddoo",
    "mdoodddddddddddoooddddddddddddddddddddddoo",
    "mdoodddddddddddoodddddddddddddddddddddddoo",
    "ddoddddddddddddoddddddddddddddddddddddddoo",
    "ddodddddddddddddddddddddddddddddddddddddoo",
    "dddddddddddddddodddddddddddddddddddddddddo",
    "omddddddddddddooddddddddddddoddddddddddddo",
    "omddddddddddddoodddddddddddodddddddddddddo",
    "omddddddddddoooddddddddddddddddddddddddddo",
    "olddddddddoooodddddddddddddddddddddddddddo",
    "oldddoooodlmdodddddddddddddddddddddddddddo",
    "olddoodddddddodddddddddddddddddddddddddddo",
    "omoodddddddddodddddddddddddddddddddddddddo",
    "ooodddddddddodddddddddddddddddddddddddddoo",
    "oldddddddddodddddddddddddddddddddddddddodo",
    "dmddddddddoddddddddddddddddddddddddddddmdo",
    "dmdddddddddddddddddddddddddddddddddddmmmoo",
    "mmddddddddmdddddddddddddddddddddmmmommmmoo",
    "mmdddddddddddddddddddddddddddddmmdoommmmoo",
    "ddoodddddddddddddddddddddooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooooo",
  ],
  [
    "odddddddddddddddmmldoomlmmmmmmmmmdooddmmdo",
    "omdddddddddddddddmmooolddooooodddoedddddoo",
    "dddddddddddddddddmmooomddooodddddoeddddddo",
    "dddddddddddddddddmmdoomddodddddddoeddddddo",
    "dddddddddddddddddmmdoommdddddddddoeddddddo",
    "dddddddddddddddddmmdoommdddddddddomddddddo",
    "dddddodddddddddddmmmoommddddddddoddddddddo",
    "dddddddddddddddddmmmoooddddddddooddddddddo",
    "ddddddddddddddooddmmoomdodddoooddddddddddo",
    "odddddddddddddodddmmoolmdooooddmdodddddddo",
    "oddddddddddddddddmmmoolmdoddddedoodddddddo",
    "omdddddddddddddddmmmoolmdddeeeedoooddddddo",
    "oddddddddddddddddmmmoommddddddedoooddddddo",
    "ddddddddddddddmddmmdoomddddooooedooooodddo",
    "ddddddddoddddddddmdooomddddoooooedoooddddo",
    "ddddddddddddddddooomoomdddddooodeeoooddddo",
    "ddddddddddddddooommmoomddddddoodeEoooddddo",
    "mdddddddddmmmdommmlmoommdddddddddEmoddmmmo",
    "lmmmmmmmmmmmmolllllmoolmmmmmmmdddEdddmmmdo",
    "ddmmmmmmmdmmodmmmlldoolmmddmmmdddEdoodddoo",
    "oooooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooooo",
    "dlmmmmmmmmmmmoemlllmoolllllmmdddelmlllllmo",
    "mmmmdddddddddmmddmmdoolmmdddddddeddddmmmdo",
    "mddddddddddddeddddmdoolmdddddddEmdddddmmdo",
    "dodddddddddodmddomddoolddoooooeeooooddddoo",
    "ooddddddddooddddddmdoomddoooooEooooddddddo",
    "ddddooddddoodoooodmdoomdoooodEmoooddddddoo",
    "ddddddooooooodoooddooomdoooeEEdooodddddddo",
    "odddddoooddddddddddooomddeEEdeeooodooomddo",
    "omdddoodddddomeeemdooomeedooooddoddddddddo",
    "omdooddddddoomddmeedooeldoooooomoddddddddo",
    "ooodmdddddooodoooomloomdoooooooddddddddddo",
    "odddddddddooomooodddoomddodddddodddddddddo",
    "omdddddddoooedooodddoomddddddddddodddddddo",
    "odddddddddodlddoddmdoomdddddddddddoddddddo",
    "oddddddddodedoodddmdoommddddddddddoooddddo",
    "ddddddddodmddoodddmdoommdddddddddddddodddo",
    "dddddddodddddddddmmdoolmmddddddddddddmmmdo",
    "dmddddoddddddddddmmdoolmmdddddddddddmmmmdo",
    "dmddddddddddddddddmooolmmdddddddddddddddoo",
    "oooooooooooooooooooooooooooooooooooooooooo",
  ],
  [
    "odddddddddddddddmlldoollmmmmmmmmmmmdddmmdo",
    "omdddddddddddddddmmoooldooooooooooddddddoo",
    "dddddddddddddddddmmooomddoooooooddoodddddo",
    "dddddddddddddddddmmooomddooodddddddddddddo",
    "ddddddddddddoddddmmooommdddddddddddddddddo",
    "dddddddddddodddddmmdoommdddddddddddddddddo",
    "dddddddddddddddddmmdooomdddddddddddddddddo",
    "dddddddddddddddddmmdoooodddddddddddddddddo",
    "dddddddddddddddddmmdooldoodddddddddddddddo",
    "oddddddodddddddddmmdoolmdooooddddddddddddo",
    "oddddddddddddddddmmdoomddddddodddddddddddo",
    "odddddddddddddddommdoomddddddooddddddddddo",
    "oddddddddddddddddmmoodddddddddoooooooddddo",
    "dddddddddddddddddmmomddddddddddoddooddddoo",
    "ddddddddddddddddddomdddddddddddodddddddddo",
    "ddddddddddddddddoomdddddddddddddoddddddddo",
    "dddddddddddddddoddoodddddddddddddodddddddo",
    "mddddddddddmmdomoodddddddddddddddodddddddo",
    "lmmmmmmmmmmmmomooddddddddddddddddooddddddo",
    "ddmmmmmmddddodddddddddddddddddddddodddmmdo",
    "ooooooooooooomdddddddddddddddddddddooommdo",
    "oooooooooooomddddddddddddddddddddddddooodo",
    "dllllmolmmmmdddddddddddddddddddddddddddooo",
    "mmddmdddddddddddddddddddddddddddddddddmmoo",
    "mddddddomdddddddddddddddddddddddddddddmmdo",
    "dooodddooddddddddddddddddddddddddddddddmoo",
    "doddddddodddddddddddddddddddddddddddddddoo",
    "dddddddddoddddddddddddddddodddddddddddddoo",
    "dddddddddooddddddddddddddddddoddddddddddoo",
    "dddddddddddoodddddddddddddddodddddddddddoo",
    "odddddddddddodddddddddddddddddddddddddddoo",
    "omdddddddddddddddddddddddddddddddddddddddo",
    "omdddddddddddddddddddddddddddddddddddddddo",
    "oddddddddddddddddddddddddddddddddddddddddo",
    "oddddddddddddddddddddddddddddddddddddddddo",
    "dddddddddddddddddddddddddddddddddddddddddo",
    "dddddddddddddddddddddddddddddddddddddddddo",
    "mdddddddddddddddddddddddddddddddddddddmmdo",
    "mmddddddddddddddddddddddddddddddddmmmmmmdo",
    "mmddddddddddddddddddddddddddddddmmmmmmmmoo",
    "ddodddddddddddddddddddddoooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooooo",
  ],
  [
    "oddddddddddddddddmlmoomlmmmmmmmdddooddmmdo",
    "omdddddddddddddddmmooolddooooododoodddddoo",
    "dddddddddddddddddmmooomddooooodddoeddddddo",
    "dddddddddddddddddmmooomddodddddddoeddddddo",
    "dddddddddddddddddmmdoolmdddddddddoeddddddo",
    "dddddddddddddddddmmdoommdddddddddolddddddo",
    "dddddddddddddddddmmdoodmddddddddoddddddddo",
    "dddddddddddddddddmmmoooddddddddooddddddddo",
    "ddddddddddddddooddmmoomdooddoododddddddddo",
    "odddddddddddddoddmmmoolmdododddmdodddddddo",
    "oddddddddddddddddmmmoolmddddddedoodddddddo",
    "oddddddddddddddddmmmoolmdddeeeedoooddddddo",
    "oddddddddddddddddmmdoommddddddedoooodddddo",
    "ddddddddddddddmddmmdoomddodooooedooooodddo",
    "ddddddddoddddddddmdooomdddddooodEdoooddddo",
    "ddddddddddddddddoodmoomddddddoodeeoooddddo",
    "ddddddddddddddooommmoomddddddoodeEoooddddo",
    "mdddddddmmmmmdommmlmoommddddddoddEmoddmmmo",
    "mmmmmmmmmmmmmolllllmoolmmmmmmmdddEmddmmmdo",
    "ddmmmmmmmdddodllllldoommmdmmmmdddEdoodddoo",
    "oooooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooooo",
    "dlmmmmmmmmmmlolmmlldoollllmmddddelllllllmo",
    "lmmddddddddddmmddmmdoolmmdmddddoeddddmmmdo",
    "mdddddddddddoedddmmdoolmddddddoemdddddmmdo",
    "dodddddddddoddoodlmdoolddoooooeeoooodddddo",
    "ooddddddddooddddddmdoomddoooooEooooddddddo",
    "ddddooddddodddooodmdoomdoooooEmoooodddddoo",
    "ddddddodooooodoooddooomdooodEEoooodddddddo",
    "ddddddoooddddddddddooomddeEedeeooooooomddo",
    "omdddooddddddmeeeddooomeemoooodmoodddddddo",
    "omdooddddddddmddmeedooeldoooooododdddddddo",
    "ooodmddddddoddooodmloomdoooooooddddddddddo",
    "odddddddddooodooodddoomddooddddodddddddddo",
    "omdddddddoooedooddddoomddodddddddodddddddo",
    "dddddddddooemddoddmdoodmdoddddddddoddddddo",
    "dddddddddodedoodddmdoodmdddddddddddooddddo",
    "ddddddddodmddoodddmdoommdddddddddddddodddo",
    "mddddddodddddddddmmdoolmddmddddddddddmmmdo",
    "mdddddodddddddddmmmdoolmmddddddddddddmmmdo",
    "mddddddddddddddddmmooolmmdddddddddddddddoo",
    "oooooooooooooooooooooooooooooooooooooooooo",
  ],
];

/* Índices das lajes que carregam marca (veio ou runa). Sai do dado, não de uma
   lista à mão: laje nova com veio entra em raro sozinha. */
const TILE_MARKED = TILE_ROWS.map((rows, i) =>
  rows.some((r) => r.includes("e") || r.includes("E") || r.includes("f")) ? i : -1
).filter((i) => i >= 0);

const TILE_BAG = (() => {
  const bag = [];
  for (let i = 0; i < TILE_ROWS.length; i++) {
    if (TILE_MARKED.indexOf(i) >= 0) bag.push(i);
    else for (let k = 0; k < 5; k++) bag.push(i);
  }
  return bag;
})();
